### ISSUE TITLE
Is their a consistent playback event, when video starts, regardless of playback format?

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/clappr#1033]
**Browser**: Multiple

**Clappr Version**: 0.2.54

Is their a consistent event that notifies when a video playback has started, regardless of format or if the content is Live or VoD, and on any device?

Also, is there an event that indicates a buffering event? If not, it would be great if it could be added?

Thanks

**Comment by leandromoreira** [comment]
Yes, we even build [a plugin for stats](https://github.com/leandromoreira/clappr-stats) where you can use or learn how to use these events.

1. [`PLAYBACK_PLAY_INTENT`](http://clappr.github.io/classes/Events.html#event_PLAYBACK_PLAY_INTENT) happens when the user hits play.
2. [`PLAYBACK_PLAY`](http://clappr.github.io/classes/Events.html#event_PLAYBACK_PLAY) happens when the playback is starting to play (or after the pause...)
3. [`PLAYBACK_BUFFERING`](http://clappr.github.io/classes/Events.html#event_PLAYBACK_BUFFERING) happens when a buffering starts and [`PLAYBACK_BUFFERFULL`](http://clappr.github.io/classes/Events.html#event_PLAYBACK_BUFFERFULL) when the buffer is full.

Please notice that all these events are not related to the player itself, they are related to playback.

**Comment by ibreakstuff93** [comment]
Thanks @leandromoreira :+1:
