### ISSUE TITLE
the sound button can’t control voice

### ISSUE THREAD

**Issue by 569934390** [clappr/clappr#1046]
in ios os,use safari browser,the sound button can't control the voice up or down!
@leandromoreira ,is that normal? or maybe some settings to do?

**Comment by leandromoreira** [comment]
It's not normal, if it's not working it's probably a bug. I'm gonna try to check this later! Thanks @569934390

**Comment by leandromoreira** [comment]
@569934390 I just tested with iphone 6s (ios 9.3.1) with http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 (at cdn.clappr.io) and it works just as expected, I mean you control the volume up or down by using the usual buttons.

**Comment by towerz** [comment]
@569934390 the player volume bar controls the output volume of the `video` tag itself. It doesn't tie into any system-wide volume control.

The volume of the `video` tag on iOS cannot be controlled using JavaScript, thus setting the volume through JavaScript calls or interacting with the volume bar doesn't have any effect. In fact, that's why the default media control implementation doesn't even show the volume control.

See [here](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW11) for more information about this matter. The important bit of info is this:
`On iOS devices, the audio level is always under the user’s physical control. The volume property is not settable in JavaScript. Reading the volume property always returns 1.`
