### ISSUE TITLE
How to work with timed metadata in HLS

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1114]
Hello,

I'm trying to use HLS stream with timed metadata with Clappr and can get tags for the hls.js playback with `player.core.getCurrentPlayback()._hls.on('hlsFragParsingMetadata', function(event, object) {...});` code. How can I get metadata with other playbacks, in flashls for example? As I understand html5 native playback should add text tracks on for metadata?

So I mean is there a common way to get metadata with clappr and work with it without writing bunch of code for each different playback?

With regards, Andrey.

**Comment by leandromoreira** [comment]
@waster there is http://clappr.github.io/classes/Events.html#event_PLAYBACK_LOADEDMETADATA what information are you expecting?

**Comment by eagsalazar** [comment]
@leandromoreira 

This is not working for me (callback never called) although audio plays back correctly and other events like `Clappr.Events.PLAYER_PLAY` work fine.   

I know this stream has HLS timed metadata because I can see it correctly being produced if I try HLS.js and their `Hls.Events.FRAG_PARSING_METADATA` event with the same m3u8 url.

```
this.player.on(Clappr.Events.PLAYBACK_LOADEDMETADATA, data => {
    console.log('PLAYBACK_LOADEDMETADATA: ', data)
})
```

For your testing, the m3u8 url is '//gimmetest1.s3.amazonaws.com/gimme1/gimme1live.m3u8'.

**Comment by leandromoreira** [comment]
You are trying to capture an event triggered at `playback` level on the `player`componenet, try this one.

```javascript
this.player.core.getCurrentPlayback().on(Clappr.Events.PLAYBACK_LOADEDMETADATA, function(data) {
  console.log('PLAYBACK_LOADEDMETADATA: ', data)
});
```

**Comment by eagsalazar** [comment]
Thanks @leandromoreira!  That did work and I am seeing the events.   However the payload does not include the timed metadata I expected.  In particular I was hoping for id3 tag data.   Also I was expecting an event at the start of each aac segment and on track changes but I am only seeing this event when the stream first loads.   This does work in HLS.js and JWPlayer so I feel confident the timed metadata is in the stream.

Am I misunderstanding the significance of this event?

**Comment by leandromoreira** [comment]
@eagsalazar if `hls.js`does that we also can do it. Today, we're doing this event by solely using [`html 5 tag`](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L139), we should expand our understanding of this `METADATA`I'm in favor of creating a new event to deal with it, since the `loadedmetada` is already something common to html5 playback.

**Comment by leandromoreira** [comment]
@clappr/core thoughts?

**Comment by towerz** [comment]
@leandromoreira you are right. The `LOADED_METADATA` event should have the same meaning as the `loadedmetadata` HTML5 video event. There are other events that `hls.js` triggers that could be translated to HLS playback events. Currently, we only trigger events that have immediate UI/metrics representation, but I have no problems with adding more events that could be useful for plugins or player implementations.

**Comment by leandromoreira** [comment]
@eagsalazar in meantime you can listen to `hls.js` events (a hack): I think it's on `this.player.core.getCurrentPlayback()._hls`

**Comment by jstnkrr** [comment]
We were able to listen for ID3 metadata using (similar to):

`if ("hls" == clappr.core.getCurrentPlayback().name) {

			clappr.core.getCurrentPlayback()._hls.on('hlsFragParsingMetadata', function(event, object) {
				
				if (!object.samples) return;

				var id3 = object.samples;

				...
			 }
}`

Bear in mind the metadata is delivered all at once as the fragments are loaded, and not in a synchronized fashio as per JW.  For us this suited our needs.

**Comment by jstnkrr** [comment]
#1285 FYI I managed to attach an ID3 metadata handler on Flash playback.
