### ISSUE TITLE
When having two player instances playing, stopping one instance triggers exiting fullscreen mode on both

### ISSUE THREAD

**Issue by Eetin** [clappr/clappr#1243]
**Browser**: 54.0.2840.100 (64-bit)

**OS**: Ubuntu 16.04 LTS

**Clappr Version**: 0.2.64

**Steps to reproduce**:

* Create two player instances and start both
* Switch first player to fullscreen mode
* Stop the second player
* I was expecting the first player to remain in fullscreen mode but it doesn't

**Comment by kslimani** [comment]
Currently, [Clappr player](https://github.com/clappr/clappr/blob/master/src/base/utils.js#L89) rely on prefixed _fullscreenElement_ [document api attributes](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#Prefixing) to detect if browser is in fullscreen : _(webkitFullscreenElement, mozFullScreenElement, msFullscreenElement, webkitFullscreenElement, webkitFullscreenElement)_ - Which explains the current "global" behaviour.

If attribute is null, then browser is not in fullscreen mode, otherwise the attribute contains the element which has requested fullscreen. 

@core : To fix/implement this behaviour, maybe add a unique id _(a data-XXX attribute ?)_ to playback element and check for it if attribute is not null ? _(not sure it is the best/elegant way to do)_

**Comment by leandromoreira** [comment]
@kslimani you're right about the reason, good catch.

**Comment by kslimani** [comment]
If i am not wrong, enter fullscreen require a user action (ie: click or touch). So if one player is in fullscreen, the scenario you describe cannot happen. (you can't click on the other player if other one is in fullscreen)

**Comment by luanraithz** [comment]
I'm sorry, I thought that there could be cases where you call the method to enter full screen.

**Comment by kslimani** [comment]
You can request fullscreen programmatically but it will be denied by the browser if it is not trigger from user click.

Another possible funny scenario could be to create a plugin which add a new button in first player media controls which trigger fullscreen on second player :smile:

**Comment by luanraithz** [comment]
Ok I think I open an PR this week about this issue, I just had do make sure what was supposed to be the behavior.
