### ISSUE TITLE
How to enable pause button for live hls?

### ISSUE THREAD

**Issue by GeorgySerga** [clappr/clappr#1315]
**Browser**: 56.0.2924.87 (64-bit), Firefox 52

**OS**: Lubuntu 16.04

**Clappr Version**: 0.2.64

**Steps to reproduce**:

I'm trying to pause and play live hls. The clappr media buttons don't include pause button, just stop. If I pause video with in-browser ui enabled with "Show controls" (firefox has pause in context menu too), then the video pauses and I can resume from the same point later. Is there a way to add pause button to clappr media controls? Thank you.

**Comment by kslimani** [comment]
AFAIK, there is currently no way to pause HLS LIVE stream (without dvr) if player use `hls.js` playback. (you should be able to pause if player use native html5 video playback, for exemple, with Safari browser on Mac OS X).

This is the default player behaviour for HLS live streams. I suspect the reason behind this choice was to save user bandwidth. (if you pause video, the playback continue to load http chunks in background, which consume bandwidth).

Thought, it *may* be possible to add such feature to player (with a new configuration parameter) to force playback to use pause (if available) for live stream.

**Comment by GeorgySerga** [comment]
I see. The in-browser play/pause that was mentioned by me above isn't real solution too: the playback is no longer than the last saved chunk - the moment it ends player jumps to the newly downloaded one. Technically, would browser allow saving chunk data into temp folder or this storage isn't big enough (must have some restrictions due to security reasons)? To me it looks like the difference between play and play/pause is piping stream on HDD when on pause and into browser, when play is enabled. If the pause had been pressed, then all the chunks end up at HDD at first, then processed by browser.

**Comment by kslimani** [comment]
It seems you are describing existing LIVE with DVR mechanisms. Except that is it implemented server side, which allow user to view past content even if they have not yet downloaded it.

Clappr can handle LIVE HLS with DVR. For example, got to [demo page](http://clappr.io/demo/) and replace `source` parameter by `https://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8?DVR`.

**Comment by GeorgySerga** [comment]
Yes, that's what I need, but no server-side DVR for me, I need to save all the data locally.

**Comment by kslimani** [comment]
AFAIK, Clappr does not have such feature. But it is maybe possible to achieve this using blob url and browser storage. (just theory), but sound like complicated !

**Comment by GeorgySerga** [comment]
Interesting thing is as far as I understand Clappr is based on `hls.js` to play hls content and considering their demo page : `http://dailymotion.github.io/hls.js/demo/` , hls.js can do this thing. Take the `https://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8` (provided above) link and insert it, start video, then press pause, chunks would load and their are available for watching later.

**Comment by kslimani** [comment]
The link provided is for tests purpose (_courtesy of [JW Player](https://www.jwplayer.com)_) : it is either a LIVE HLS stream or LIVE+DVR HLS stream depending on if you add or not the `?DVR` query parameter.

You are right about `hls.js`. For HLS stream playback resolving, Clappr player proceed the following :

* If `hls.js` library is supported by web browser, it use it for playback. (_Firefox, Chrome, ..._)
* If web browser is Safari, it uses native HTML5 video element. (_you should see in this scenario the pause button instead of stop_).
* Otherwise, if web browser has Flash plugin, it use Flash HLS playback. (_Old Internet explorer browsers_)

In `hls.js` playback scenario, for LIVE stream without DVR, Clappr developpers decided that behaviour is to stop video (_not pause_). (_personally, i support this choice 😄_ ) For LIVE stream with DVR enabled, then player allow to : pause video, seek video, and display a "back to live" button. (_It should also be available if playback if FLASH HLS_).

I think it should be technically possible to add a feature, for example, using a new playback parameter named `stopOnPause` (_which default to false_), that if set to true, then pause video instead of stop if using `hls.js` playback (_and maybe also flash hls playback_).

**Comment by GeorgySerga** [comment]
Yes, I was able to modify the js file to get caching behavior working. Also there is issue on browser buffering capacity for future reference: https://github.com/dailymotion/hls.js/issues/1030 .

**Comment by TroyDota** [comment]
@kslimani how do we enable the buttons regardless, which trigger player.pause() and player.play() and then we control the hls via the events triggered, such as 
`onPlay: () => {
            if (isPaused) {
                isPaused = false;
                player.load(player.options.source);
            }
            player.configure({ poster:  '' });
            player.getPlugin('poster').$el[0].style = "";
        },
        onPause: () => {
            var canvas = document.createElement("canvas");
            var options = player.getPlaybackQuality();
            var bestLevel = options[options.length-1].level;
            canvas.width = bestLevel.width;
            canvas.height = bestLevel.height;
            var ctx = canvas.getContext('2d');
            ctx.globalAlpha = 0.5;
            ctx.drawImage($("#player video").get(0), 0, 0, canvas.width, canvas.height);
            player.configure({ poster: canvas.toDataURL() });
            player.core.activePlayback._hls.stopLoad();
            isPaused = true;
        },`
