### ISSUE TITLE
Browser.isChrome is broken on iOS device

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1355]
**Browser**: Chrome Version 57.0.2987.137

**OS**: iOS 9.3.5 (iPad mini)

**Clappr Version**: latest

**Steps to reproduce**:

The current detection code is :

```
Browser.isChrome = /chrome/i.test(navigator.userAgent)
```

The navigator.value is :

```
Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/57.0.2987.137 Mobile/13G36 Safari/601.1.46
```

It seems that latest versions of Google Chrome is now called CriOS on iOS devices ?

EDIT: also broken on my iPhone 5S.

**Comment by towerz** [comment]
@kslimani is this actually an issue? Technically, the Chrome browser on iOS is just a wrapper around the `WKWebView` component, which actually behaves as a Safari, since it uses the Safari stack.

Why do you need to recognize Chrome for iOS specifically? Is there some player code which actually depends on this?

**Comment by kslimani** [comment]
@towerz  : yes it is an issue. You need to detect Chrome on iOS, for example, in Chromecast plugin. (see [comment](https://github.com/clappr/clappr-chromecast-plugin/pull/12#issuecomment-292584182)).

**Comment by towerz** [comment]
@kslimani indeed, you're correct. This should enable some plugins to be enabled specifically for Chrome on iOS. Actually, I wasn't aware that the Chromecast plugin works on Chrome for iOS. Thanks for pointing this out.
