### ISSUE TITLE
HLS is blocked on Firefox and Chrome when page is loaded with https

### ISSUE THREAD

**Issue by frank717** [clappr/clappr#1391]
Hi,
using http everything is fine, but when I load my page with https Firefox (53.0.2) and Chrome (58.0.3029.96) seem to block the stream.

OK:
[http://www.dentaurum.de/deu/ids-2017-29720_29767.aspx](http://www.dentaurum.de/deu/ids-2017-29720_29767.aspx
)
Not OK:
[https://www.dentaurum.de/deu/ids-2017-29720_29767.aspx](https://www.dentaurum.de/deu/ids-2017-29720_29767.aspx)

`<script type="text/javascript" src="//cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>`

```
<div id="player">
</div>
<script>
    var player = new Clappr.Player({sources: [{source: "http://62.113.210.172/dentaurum-vod/_definst_/mp4:mediathek/ids2017/Dentaurum-Highlights.mp4/playlist.m3u8"},{source: "rtsp://62.113.210.172:554/dentaurum-vod/_definst_/mp4:mediathek/ids2017/Dentaurum-Highlights.mp4"}], parentId: "#player", poster:"", allowUserInteraction: true, height:380 , width:675, autoPlay: true});
</script>
```
What can I do?
Thank you!

**Comment by kslimani** [comment]
@frank717 Browser which block "mixed" content is an expected behaviour. (_which is not related to Clappr_).

If your pages are served in HTTPS, then you must also server your video content over HTTPS protocol or it will be blocked by browsers.

Here more info about mixed content policies :

* https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
* https://blogs.msdn.microsoft.com/ie/2011/06/23/internet-explorer-9-security-part-4-protecting-consumers-from-malicious-mixed-content/
* https://security.googleblog.com/2011/06/trying-to-end-mixed-scripting.html

**Comment by frank717** [comment]
OK, thank you for this information.
