### ISSUE TITLE
Stream mp3

### ISSUE THREAD

**Issue by JeanSauzem** [clappr/clappr#1448]
Do you have the mp3 stream in the player?

**Comment by leandromoreira** [comment]
Hi @JeanSauzem I think clappr does play mp3. I went to http://clappr.io/demo/ and try the following code.

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 60,
  width: 640
});

player.attachTo(playerElement);

```

**Comment by JeanSauzem** [comment]
Hi @leandromoreira "http://104.41.45.119:1935/leadlovers/mp3:Central.mp3/playlist.m3u8" Using the following link, the player is only loading

**Comment by kslimani** [comment]
@JeanSauzem the demo page is using Clappr version 0.2.66. I think this playlist should work with version 0.2.67 because it use hls.js 0.7.9 which should properly load your playlist.

**Comment by leandromoreira** [comment]
[Mp3 doesn't seem to work on W10](https://github.com/video-dev/hls.js#not-supported-yet) though.

**Comment by kslimani** [comment]
@leandromoreira you are correct for Window with IE and Edge. But with Chrome it work.

**Comment by JeanSauzem** [comment]
But using m3u8 file with a video works, playlist is just the name of the file, the player does not read m3u8 file containing only audio

**Comment by kslimani** [comment]
@JeanSauzem i am aware that playlist.m3u8 is manifest file 😸 

As explained above, the Clappr demo page is loading the version 0.2.66 of Clappr player (_which does NOT support your audio playlist because it internally NOT use the latest version of hls.js library_).

To make your audio source to work with Clappr, you need to use the version 0.2.67 (wich uses the latest hls.js library version 0.7.9). As prrof of concept, just try your hls source [here](http://streambox.fr/mse/hls.js-0.7.9/demo/).

Please also note that mp3 audio codec is not supported yet by hls.js with Windows on IE and Edge browsers. But it should work with Chrome (i did not test Firefox).

**Comment by JeanSauzem** [comment]
Thank you @kslimani
