### ISSUE TITLE
HLS level restart after loop

### ISSUE THREAD

**Issue by hlozancic** [clappr/clappr#1449]
**Browser**: any browser

**OS**: any os

**Clappr Version**: latest

**Description**:

Clappr will restart HLS level to 0 after loop even if higher level was loaded during video playback. Check fiddle for more info (http://jsfiddle.net/jL66pops/)

**Steps to reproduce**:

* Check the issue here or follow the steps below: http://jsfiddle.net/jL66pops/
* Load any .m3u8 HLS playlist with at least 2 levels
* Set HLS config to load level 0 at start and loop to true
* Wait until clappr fetches next level
* After video loops, level will jump back to 0 instead staying on level 1

Issue is reproduced on http://cdn.clappr.io/

**Comment by ibarisic05** [comment]
+1

**Comment by Sheby** [comment]
I have the same problem, any word on this?

**Comment by kslimani** [comment]
It should be possible to partially fix this issue, but keep in mind that it will be only if player is using HJSJS playback. For native playback (iphone for example) i am not sure we can change the default behaviour.

**Comment by hlozancic** [comment]
Tried without clappr using only HLSJS

http://jsfiddle.net/jL66pops/1/

Same issues... How to configure HLSJS to continue playing loaded level?

**Comment by kslimani** [comment]
@hlozancic there is a [`startLevel`](https://github.com/video-dev/hls.js/blob/master/doc/API.md#startlevel) configuration option and a property in HLSJS which allow you to configure default star level. Since Clappr is listening to hls [LEVEL_SWITCH](https://github.com/video-dev/hls.js/blob/master/doc/API.md#runtime-events) event, i think it is possible to create a feature to keep current level and then set it as start level if Clappr Player `loop` option is set to true.

**Comment by hlozancic** [comment]
I'm already using startLevel config... Will try to listen on level_switch and set level manually to higher when switched or something... Will send fiddle later today

**Comment by kslimani** [comment]
using startLevel config isn't enough, you have to lisent to LEVEL_SWITH event.

For example, let's suppose you set start level to 1, then video play, and for an XYZ reason player switch to level 0 at end, then on loop video will start from level 1 instead of level 0.

This is why i think a solution is to listen to LEVEL_SWITCH event to store the current level, and set it as startLevel **only** if player `loop` option is set to true.
