### ISSUE TITLE
How to force Clappr player to stay fullscreen after change video?

### ISSUE THREAD

**Issue by RussellSk** [clappr/clappr#1467]
How to force Clappr player to stay fullscreen after change video?
I write a function that triggered on PLAYER_ENDED event, function loads next video with this `load` method:

    enter code here`enter code here`player.load([{source: 'video_url_exmpl'}], null, true);

But when event was triggered and the new video loaded player cancels Fullscreen mode. I set up option: 

    exitFullscreenOnEnd: false,

I write a plugin that supposes to toggle fullscreen but browser throw a warning message:

    Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture

Here is my Clappr player initialization and settings:

     player = new Clappr.Player({
            source: sourceUrl,
            parentId: "#player",
            autoPlay: true,
            width: '100%',
            height: '100%',
            exitFullscreenOnEnd: false,
            playInline: true,
            recycleVideo: Clappr.Browser.isMobile,
            poster: '',
        }).on(Clappr.Events.PLAYER_ENDED, function() {
               player.load([{source: 'video_url'}], null, true);
              }
        });

**Comment by kslimani** [comment]
@RussellSk , please note that `playInline` and `recycleVideo` are [playback options](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#playback-configuration). (_and therefore must be passed in 'playback' property_).


The Player `exitFullscreenOnEnd` option is handled by an internal plugin called [end_video](https://github.com/clappr/clappr/blob/master/src/plugins/end_video.js) which listen to `CONTAINER_ENDED` and `CONTAINER_STOP` events to exit (or not) fullscreen at end of the video. (_default is true_).

With the current Clappr internal mechanisms it is not possible to stay in fullscreen if you change video source with `load()` Player method. The technical reason is when the source change, player "core" will destroy the current container and build a new one for the new source. (_though i did not test on mobile with recycleVideo option enabled and `exitFullscreenOnEnd` set to false_).

Another technical reason _may_ be because the video source url _may_ be removed from video element at the end of video or if video is stopped. (_depending on the source format and playback capabilities_).

So, in an **HTML5 video scenario**, to change video source without exit fullscreen, you may needs to work directly with the playback video element. (_which is "hacky", but should be possible_).

**Comment by RussellSk** [comment]
@kslimani Thank you for your reply, but how can I load in HTML5 next video or change video "on the fly" without reloading core of the player and therefore stay in Fullscreen mode? Tell me where to start digging...
Or it is impossible?

**Comment by kslimani** [comment]
@RussellSk go to [Clappr demo page](http://clappr.io/demo/) and try the following code :

```javascript
var player = new Clappr.Player({
  parentId: "#player-wrapper",
  source: 'http://clappr.io/highline.mp4',
  height: 360,
  width: 640,
  exitFullscreenOnEnd: false,
  playback: {
    playInline: true,
    recycleVideo: true,
  },
  events: {
    onEnded: function () {
      var setSource = function (newSrc) {
        this.core.options.source = newSrc;
        var container = this.core.getCurrentContainer();
        var playback = this.core.getCurrentPlayback();
        if (container) {
          container.options.source = newSrc;
        }
        if (playback) {
          playback.options.source = newSrc;
          playback._setupSrc && playback._setupSrc(newSrc);
        }
      }.bind(this);

      // Set another .mp4 source and start again player
      setSource('https://static.playmedia-cdn.net/resources/sample/h264_sintel_trailer-1080p.mp4');
      this.play();
    }
  }
});
```

Please note this code is an ugly trick which *may* let some player components (_like plugins_) in an inconsistent state. This work only if source are in same format (_ie: all source are .mp4 files_).
But should give you some hints to where to start to dig.

**Comment by kslimani** [comment]
Another approach could be also to create one or several Playback plugin which can take a list of video as option and play video one after one. (_without using core.load() and working directly with html5 video element_).

**Comment by towerz** [comment]
We're working on a change in the internal player structure to prevent destroying the playback in most cases. 

Actually, we already have done this partially in our chromecast implementation, and we’ll probably port this back into Clappr this week. We just need to ensure the new behavior won’t break anything.

**Comment by RussellSk** [comment]
@kslimani Thank you for your help, your example solve the issue. :)
@towerz How can I contribute to the project, what can I do? If you have some exercises. 

Thanks.

**Comment by RussellSk** [comment]
@kslimani I'm sorry for asking you again but when I'm using .**m3u8** format, the player plays everytime the same source URL... Without changing, Is there some additional function in Clappr that extract valid url for core?

**Comment by kslimani** [comment]
@RussellSk 

Updated code for hls playback : 

```javascript
var player = new Clappr.Player({
  parentId: "#player-wrapper",
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  height: 360,
  width: 640,
  exitFullscreenOnEnd: false,
  playback: {
    playInline: true,
    recycleVideo: true,
  },
  events: {
    onEnded: function () {
      var setSource = function (newSrc) {
        this.core.options.source = newSrc;
        var container = this.core.getCurrentContainer();
        var playback = this.core.getCurrentPlayback();
        if (container) {
          container.options.source = newSrc;
        }
        if (playback) {
          playback.options.source = newSrc;
          playback.options.src && (playback.options.src = newSrc);
          playback._setupHls && playback._setupHls();
          playback._setupSrc && playback._setupSrc(newSrc);
        }
      }.bind(this);

      // Set another .mp4 source and start again player
      setSource('http://www.streambox.fr/playlists/x31jrg1/x31jrg1.m3u8');
      this.play();
    }
  }
});
```
