### ISSUE TITLE
Before request event

### ISSUE THREAD

**Issue by elhampour** [clappr/clappr#1494]
i am in need of before request event for every ts part in hls format, how can i achieve this ?

**Comment by kslimani** [comment]
Clappr is internally using hls.js library for HLS source playback. You should take a look at their [API event](https://github.com/video-dev/hls.js/blob/master/doc/API.md#runtime-events).

_Note that for some mobile devices, it is the native html5 video element which is used (instead of hls.js) and you may not be able to achieve it in this scenario._

**Comment by elhampour** [comment]
yes i have found it.

var player = new Clappr.Player({
            source: "494f6d4f-7900-4356-8b79-73b6fa02ccc5-master.m3u8",
            parentId: "#player",
            playback: {
                hlsjsConfig: {
                    maxBufferSize: 5,
                    xhrSetup: function (xhr, url) {
                        console.log(url);
                        url = url.replace('http://v1', 'http://v1');
                        xhr.open('GET', url, true);
                    }
                }
            },
            plugins: {
                'core': [LevelSelector]
            }
        });

**Comment by shankar-bavan** [comment]
@elhampour Is this method works on iphone?
