### ISSUE TITLE
Feature request: poster image by frame second

### ISSUE THREAD

**Issue by chrisprog20** [clappr/clappr#1497]
Hi folks,

our editors use clappr to publish videos. As they want posters on their video they make a screenshot of the video, load it up and apply then the file path of it to the Clappr.Player poster property.
As this takes a lot of time for multiple videos it would be quite convenient if they could just enter a frame second number (e.g. 3) and this number then is used to show the frame second of the video as a poster.

Would be great if you could feedback about this. :)

Cheers
Christian

**Comment by towerz** [comment]
Hi @chrisprog20, this seems to be a nice feature for the poster plugin. Thanks for the idea.

My only concern is that in order to show the frame corresponding to the second of the video, the player should make some requests to access the video metadata and then render it to a image. This could be costly for processing, and perhaps shouldn't be used for production environments. But I think it could be useful for a publishing environment.

Are you planning to implement that on the Poster plugin? Have you had any ideas on how to enable this for the end user?

**Comment by kslimani** [comment]
Implementing such feature on player side may lead to heavy costs (_especially on server side_).

I think a better approach could be to create a micro service application which automatically (pre-)generate thumbnails and serve them as static image files (possibly with caching). It could also generate an image at regular interval for live streams. And serve a default placeholder image if thumbnails is not yet available.

This solution should reduce server cost as only application access video to generate images, and since it is server side, it should be easy to scale.

Another advantage is it work for any video player which support poster image.

**Comment by chrisprog20** [comment]
@towerz:
Thank you for your answer. It was more a suggestion from my site. Unfortunately I did not had any idea to realize this - but it is good to learn some approaches on that. Unfortunately I am not able to provide this feature at the moment - maybe in future, but currently I am sorry that I have no time left to do that.

**Comment by chrisprog20** [comment]
@kslimani:
Thank you also for your suggestion: I like the idea of the microservice to reduce processing costs.
Unfortunately I have currently no time left to do that - maybe in future.

**Comment by towerz** [comment]
@chrisprog20 I agree with @kslimani about having a server side solution. This seems to be an ideal solution.

But I still like the idea of having a plugin for extracting some video thumbs on the client side, but only for publishing environments, where an editor wouldn't need to upload the video to choose a poster image. As I said, this shouldn't be used for production/delivery environments, but it would still be useful as a tool for publishing.

**Comment by eutychus** [comment]
There are a few ways to accomplish this... what we do is launch a clappr player with an event for pause, get the timecode, then fetch the fragment back from the server from the source file... using a command line like this:

ffmpeg -ss __FLOAT_OFFSET_IN_SEC__ -i __SOURCEFILE__ -frames 1 -f image2 -q:v 2 __OUTFILE.JPG__

Our client can then approve the snapshot or continue on.

We capture from the source as we want a high quality capture and the player is typically playing back a multirate rendition at a lower bit rate than the source.

Another option is to play back the video and render it onto a canvas, then capture the canvas output from the client side.

**Comment by chrisprog20** [comment]
@towerz: What do you think about @eutychus approach?
I like it: You just provide the snapshot yielded by 
ffmpeg -ss FLOAT_OFFSET_IN_SEC -i SOURCEFILE -frames 1 -f image2 -q:v 2 OUTFILE.JPG

where the editor only provides FLOAT_OFFSET_IN_SEC and SOURCEFILE
