### ISSUE TITLE
Advice on writing a seek/switch playback plugin

### ISSUE THREAD

**Issue by chriswiggins** [clappr/clappr#1577]
Hopefully a quick question to point me in the right direction!

I'm working on a playback plugin using Fragmented MP4 over web sockets (which I'll release shortly) to get low-latency live video.

While this is great for live, I still want to be able to utilise `hls.js` for the sliding window functionality. 

What I'd like to do is the following:

- Set up both the `fmp4` and `hls.js` playback plugins and default to the `fmp4` playback (auto play)
- Show the duration on the seek bar as the duration of the hls playlist (the sliding window)
- Listen to the seek event, if outside the current buffer window of `fmp4`, switch playback to `hls.js` and seek to that time. Seeking back to live should switch back to `fmp4`.

What classes do I need to override in order to do this? I've been trawling through the source however I can't quite work out what events I need to override in order to do this. I'm thinking I'll need to extend the `hls.js` plugin, the `seek_time` plugin, maybe the `dvr_controls` plugin and potentially even the `media_control` core. 

Is there anything else I could do to do this? Maybe override `hls.js` and `fmp4` to emit a different event to `TIMEUPDATE` and then trigger this myself in the plugin?

Any and all ideas greatly appreciated!

**Comment by towerz** [comment]
@chriswiggins I believe you'll need a playback proxy, or at least a plugin that manages the playback change handling.

Since the states you need to manage are only related to the playback, I think using a playback proxy will work better for you. Basically, you need to implement the `Playback` interface, implementing the correct `canPlay` checks you want. This implementation will have instances both `hls.js` and `fmp4` playbacks as properties, and would set either one as active depending on the sliding window state. You just need to forward the events and methods from/to the active playback instance and I think that should do it.

Let me know if this works for you or if you have any questions.

**Comment by chriswiggins** [comment]
@towerz sorry for the late reply (and thanks stalebot for the reminder!)

I did exactly as you specified and it seems to work really well. All I need to sort out is my buggy playback underneath the playback proxy 👍

**Comment by towerz** [comment]
@chriswiggins glad to know it worked. Please let me know if you need further assistance.
