### ISSUE TITLE
Smart tv 

### ISSUE THREAD

**Issue by Impulso902** [clappr/clappr#1589]
hi , i have a problem with smart tv . the streams hls don't start on all smart tv, who can help me?

**Comment by leandromoreira** [comment]
Hey @Impulso902 it's **very hard** to support all SmartTV brands (plus older vs newer), I saw some cases where people had to create 7 different `hls manifests` due to the requirements of each TV (ie: a TV X requires you to explicitly inform the `VERSION : 3` where others will fail if you do that), so you need to analyze case by case. And there is some TV that is not able to play HLS at all.

People at GPAC did an amazing job describing [each HLS version.](https://www.gpac-licensing.com/2014/12/08/apple-hls-technical-depth/) But I still think you'll need to go case by case and looking,  testing and debugging each Brand / Model / Year.

**Comment by matheusrufca** [comment]
Hello, @Impulso902 .
On Tizen SmartTV devices Clappr stop playing HLS streamings after update #0.2.78.
You can try using versions above 0.2.78 and see if works. 
I'm using on Tizen and WebOS devices and is working good with HLS streams.
