### ISSUE TITLE
Method to check subtitles support of playback

### ISSUE THREAD

**Issue by andrefilimono** [clappr/clappr#1616]
Maybe it is worth to add a new method to check if playback supports subtitles thus other playbacks can override it.

Currently, it can be done by overriding [isHTML5Video](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L469), but I think it should have a more appropriate name for this, e.g. `isSupportSubtitles`.

And for `html5 video` playback this code will be:
```js
get isSupportSubtitles () {
  return this.isHTML5Video
}

_checkForClosedCaptions () {
  if (this.isSupportSubtitles && !this._ccIsSetup) {
    ...
  }
}
```

**Comment by kslimani** [comment]
@andrefilimono just to be sure, do you need to know  : if a playback can "maybe" have some subtitles ? or if there are some subtitles with  source ?

For subtitle availability, there is a `PLAYBACK_SUBTITLE_AVAILABLE` event. (listen by internal CC plugin).

This is because for some source, playback do not know immediatly if there are subtitles, but only after video has started to play _(for example captions embeded in hls source)_.

Also a method could be added in Playback base class (override by playback class) which return a boolean to indicate if playback handle closed caption. _(for example: canHandleSubtitles() )_

**Comment by andrefilimono** [comment]
@kslimani Thanks for your answer!
I was talking about a method that indicates if playback can handle closed captions.
