### ISSUE TITLE
Preview frames while dragging progress bar

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1617]
Is there any way to preview the frames of a live stream while dragging progress bar? (like hls.js)

**Comment by towerz** [comment]
@hijuuijj it's not supported right now. Actually, this is not an hls.js feature, but a side effect of dragging the native player seek bar causing a seek event. 

Since the playback doesn't resume while the scrubber is being dragged, the result is that the video actually stays paused and due to the seek events, it displays some "preview" frames during the drag.

This could be done by extending the MediaControl and change it to add this behavior, but it's not a feature we support right away.
