### ISSUE TITLE
google dfp pre-roll video ads 

### ISSUE THREAD

**Issue by mufin695** [clappr/clappr#1648]
Does anyone know if google dfp pre-roll video ads work with clappr / have a working example. I haven't been able to find much information. I have my ads working with just HTML <video> tag

**Comment by kslimani** [comment]
@mufin695 i have released a new version of my [Clappr Google IMA pre-roll plugin](https://github.com/kslimani/clappr-google-ima-html5-preroll). It is still experimental, but i may fits your needs.

**Comment by leandromoreira** [comment]
Hey @kslimani how about we add it to https://github.com/clappr/clappr/blob/master/doc/EXTERNAL_PLUGINS.md

**Comment by yijunjun1** [comment]
{autoPlay: true} attribute It will not work when initialization. Can you tell me?

**Comment by kslimani** [comment]
@yijunjun1 : if you are using [this plugin](https://github.com/kslimani/clappr-google-ima-html5-preroll), please note that it require having `autoPlay: false`. You can control the autoplay using the **plugin** `autoStart` option (which default tot true). Please refer to [plugin usage](https://github.com/kslimani/clappr-google-ima-html5-preroll#usage).

It is a temporary limitation for this plugin which is due to current Clappr autoplay internal mechanisms. (hopefully, will be fixed in next major release).
