### ISSUE TITLE
Clappr, Change version numbers

### ISSUE THREAD

**Issue by ewwink** [clappr/clappr#1663]
this is not issue just suggestion. I think Clappr already mature and needs to change version number from 0.2.xx to 1.2, 2.0, 9.1 etc... as did Firefox few years ago.

**Comment by towerz** [comment]
@ewwink we're working on an architecture revision of the player, and we were reserving the next version numbers to follow these revisions.

Since we are a little shorthanded, this revision is taking a little bit of time, but I think we'll have 2 to 3 minor revisions until we promote it to 1.0. After that, we'll follow the major/minor/patch version numbering as we should.
