### ISSUE TITLE
Change playback from FlasHLS to HLS

### ISSUE THREAD

**Issue by ewwink** [clappr/clappr#1668]
can I change it? the following way not work

`player.configure({plugin: [Clappr.HLS]})`

or with plugin

```
this.core.containers[0].plugins.forEach(function(plugin){
  if(plugin.name == 'flashls') plugin.destroy()
})
this.core.containers[0].configure({plugin: [Clappr.HLS]})
```

**Comment by kslimani** [comment]
@ewwink Clappr default behaviour is to user HLSJS playback if browser fullfills requirements. If it is not supported by browser, then it attempt to fallback to FlashHLS (only if flash plugin installed).

So basically, you have nothing to do, just omit the `plugin` player configuration option.

**Comment by ewwink** [comment]
but when using Firefox desktop with Flash player set to "Ask to Activate" and domain has no permission to run flash the source will not played and Firefox not ask me to activate flash just see the black screen, that the reason I want to switch.

**Comment by flavioribeiro** [comment]
what source video url you're trying @ewwink? If you're using a Firefox that's older than 42 (which was released in Nov, 2015) you probably don't have MSE support on it and the `canPlay` method on hls.js will return `False`, falling back to the flash player. Let us know if that's the case or if this issue was already solved on your side.
