### ISSUE TITLE
HLS EXT-PROGRAM-DATETIME WITH DISCONTINUTY

### ISSUE THREAD

**Issue by ctaity** [clappr/clappr#1671]
When the m3u8 has EXT-X-DISCONTINUTY WITH EXT-PROGRAM-DATETIME hls playback has a `fragments[0].rawProgramDateTime ` is  undefined. 

The correct way to get ext program datetime is 

` data.details.programDateTime `

heare my patch:

```
_onLevelUpdated(evt, data) {
    this._segmentTargetDuration = data.details.targetduration
    this._playlistType = data.details.type || null

    let startTimeChanged = false
    let durationChanged = false
    let fragments = data.details.fragments
    let previousPlayableRegionStartTime = this._playableRegionStartTime
    let previousPlayableRegionDuration = this._playableRegionDuration

    // #EXT-X-PROGRAM-DATE-TIME
    // console.log(data.details.programDateTime.toString());
    if (data.details.programDateTime)
      this._programDateTime = data.details.programDateTime;
```

**Comment by leandromoreira** [comment]
is this something wrong on clappr?

**Comment by ctaity** [comment]
Yes, when the m3u8 has a #EXT-DISCONTINUTY and the tag #EXT-PROGRAMDATETIME is in the middle for example of the manifest, the following code, dont works.
```
if (fragments[0].rawProgramDateTime)
      this._programDateTime = fragments[0].rawProgramDateTime
```

But this code:

```
if (data.details.programDateTime)
      this._programDateTime = data.details.programDateTime;
```
Always works to get de program date time.

This lines of code are in: https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js

Start on line : 447

**Comment by leandromoreira** [comment]
Thank you @ctaity ! :)

**Comment by joaopaulovieira** [comment]
Hi @ctaity! 

Running [hlsjs-playback](https://github.com/clappr/hlsjs-playback) locally, I was not able to get any information when I tried to access via `data.details.programDateTime`. On the other hand, when I accessed via `fragments[0].rawProgramDateTime` it always returned the expected (even when the m3u8 have the EXT-X-DISCONTINUTY tag).

Would it be possible for you to share one media with the problem you reported?

If you can too, could you share some documentation about `data.details.programDateTime` as well? I didn't find anything about it in the [hls.js documentation](https://github.com/video-dev/hls.js/blob/master/docs/API.md).

**Comment by ctaity** [comment]
Yes, the hls tag is #EXT-X-PROGRAM-DATE-TIME, https://tools.ietf.org/html/draft-pantos-http-live-streaming-12#section-3.4.5
The tag retain the timestamp when the streaming started, and is useful to do some thigs in live streaming.

**Comment by joaopaulovieira** [comment]
Yes, is true that this data is very useful for many things but your report (as I understand it) is that the Clappr currently cannot get this data via `fragments[0].rawProgramDateTime` when there is also another `#EXT-DISCONTINUTY` tag in the `m3u8` and that it would be possible to get this data in this case via `data.details.programDateTime`, correct?

However, reference `data.details.programDateTime` was not available in the tests I performed, but the reference`fragments[0].rawProgramDateTime` it was.  I only had access `programDateTime` via `fragments[0].programDateTime`.

See the print of my console below:

![Screen Shot 2020-09-20 at 11 51 04](https://user-images.githubusercontent.com/5631063/93714231-a77d4800-fb37-11ea-83c3-2a6642ca6480.png)

Just to make sure I understand. Your question is:

(1) The reference `fragments[0].rawProgramDateTime` is not available in one case that you need.

or

(2) The reference you need is `fragments[0].programDateTime` instead of `fragments[0].rawProgramDateTime`.

If it's (1), it would be good if you made available an `m3u8` in which it is possible to use `data.details.programDateTime`, because I was unable to obtain anything in the media that I used for testing.

If it's (2), it's better to open another issue requesting this data in the [@clappr/hlsjs-playback](https://github.com/clappr/hlsjs-playback) project (And even a PR adding this feature 🙂).

**Comment by ctaity** [comment]
The bug occurs, when the encoder (nginx - rtmp) has a discontinuty and put the tag  #EXT-PROGRAMDATETIME, in the middle of the manifest.

XXX
XXX
XXX
XXX
XXX
#EXT-PROGRAMDATETIME
XXX
XXX
XXX


when the tag is in the top of the manifest, works well.

When this occur, fragments[0].rawProgramDateTime is undefined. I think the case 2 is better to fix this bug.

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
