### ISSUE TITLE
How to disable embed plugins?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1675]
I see how to add an external plugin. But how to disable, for example, a poster-plugin, if i want to use its altered version instead?

**Comment by kslimani** [comment]
I think that if you name your plugin the same name, it will overide hte internal one (to confirm).

PS: by name, i mean the value returned by [name()](https://github.com/clappr/clappr/blob/master/src/plugins/poster/poster.js#L15) getter method.

**Comment by leandromoreira** [comment]
I also think that if you just declare a plugin it'll be put first at the plugin list which makes it preferable over the other.

**Comment by towerz** [comment]
@leandromoreira You're right. External plugins are always prioritized in relation to built-in plugins.

The plugin `Loader`always uses the property `name` as the key to a plugin. So, in order to override an internal plugin, you just need to use your own custom plugin with the same `name` as the internal plugin, as @kslimani answered.

If you just want to disable a given plugin instead of overriding it, you just need to call `disable` on the plugin instance.
