### ISSUE TITLE
Change color, font, etc. of closed captions?

### ISSUE THREAD

**Issue by sheriffmarley** [clappr/clappr#1701]
Hi,

is it possible to change the color, font, background-color, etc. of the closed captions? 

I can't find the corresponding html classes for it nor anything in the docs.

**Comment by sheriffmarley** [comment]
So it's not possible to just change the value with css?

**Comment by oliwarner** [comment]
Looking at ours, they're just rendered as `div.plyr__captions>span+.plyr__caption` so pretty simple to bolt some styling onto. You don't need to dig any further unless you want to do special things (like per-actor colours).

**Comment by sheriffmarley** [comment]
Where did you find them? I took a look at every div i could find but no `plyr_caption` anywhere

**Comment by bikegriffith** [comment]
With the built-in plugin, you can only change a few things with CSS (namely colors), but even for that you'll have to reach into the ::cues shadow DOM because it simply uses the browser's native `<track>` element rendering.  If you're trying to change position/layout of the captions, you need to go down the route of building your own plugin that renders the cues explicitly based on hls.js track events.
