### ISSUE TITLE
HLS Stream + external subtitles?

### ISSUE THREAD

**Issue by katsar0v** [clappr/clappr#1761]
I am using clappr player together with this nginx module - https://github.com/kaltura/nginx-vod-module
Unfortunately there is only one subtitle language available by default - English. I want to be able to change the label as well support multiple subtitles. Is there a way to support external subtitles using `Clappr`?

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#playback-configuration

**Comment by katsar0v** [comment]
Is this compatible with hls streams?

**Comment by leandromoreira** [comment]
I think this works cross all playbacks that relies on html5 https://github.com/clappr/clappr/blob/9a2646772fae9b1b17bfdedb50179bb38a83658e/src/playbacks/html5_video/html5_video.js#L605

**Comment by kslimani** [comment]
@katsar0v i think internal CC plugin is currently broken with hls playback because text track api has been changed in hls.js library since the last release/modification of the plugin. (and i am not sure if external track was implemented/checked at this time for this playback).

But with the new textTrack api methods, event added to hls.js latests release, it should be relatively simple to apply modifications to the internal plugin.

**Comment by katsar0v** [comment]
When an HLS Stream is used, mostly the subtitles come from the stream itself. In my case it was not documentet how to use multiple subtitles, but I got this --> https://github.com/kaltura/nginx-vod-module/issues/950
