### ISSUE TITLE
Is there a way to obtain current playback level?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1763]
I want to know current level, but _playback.currentLevel_ is always -1 when set to "auto"
I can take the info from PLAYBACK_BITRATE event, but it seems to be not always accurate when _playback.currentLevel_ is set manually. And I'd like to know that without waiting for the quality to change.
Is there a way to obtain actual playback level at every moment?

**Comment by towerz** [comment]
@sapolio the only way to have the current playback level is to use the `PLAYBACK_BITRATE` event.

Since you're having issues with it not being accurate when the `playback.currentLevel` is set manually, I recommend using a mixed approach: use `playback.currentLevel` and if it's set to -1, use the one from the `PLAYBACK_BITRATE` event.

**Comment by ewwink** [comment]
`-1` is equal to `auto`
