### ISSUE TITLE
Chromecast button no longer available?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1816]
I have tried this code: https://github.com/clappr/clappr-chromecast-plugin
but it doesn't show the Chromecast button in Windows 10 or Android 9.
My Chromecast is always on; If I open Chrome for Windows and I click "Send", I see the Chromecast connection ... also with Netflix for Android.

**Comment by towerz** [comment]
@hijuuijj It seems like the Chromecast requirements have changed, and you need to serve your content over HTTPS to have access to the Chromecast extension.

I'll try to confirm that, and will let you know if there's something wrong with the plugin. Other than that, the plugin needs to be updated to use the CAF sender library (v3) instead of the v2.

**Comment by hijuuijj** [comment]
Is there any news? I miss Chromecast plugin

**Comment by leandromoreira** [comment]
keep it open

**Comment by towerz** [comment]
@hijuuijj @leandromoreira I checked the Chromecast plugin [demo page](https://clappr.github.io/clappr-chromecast-plugin) and it worked on all devices.

I confirmed that there is a requirement to serve the page over HTTPS (the button won't work on HTTP URLs). There's no need to update the sender library.

Another thing to be aware of is that the Receiver should be published, or the cast button won't be shown. 
 
![Screenshot 2019-09-19 16 28 51](https://user-images.githubusercontent.com/989801/65274924-d747d900-dafa-11e9-81c5-82988963f678.png)

If you use the default Clappr Receiver (9DFB77C0) you'll be ok. If you are running local tests, make sure you're loading the sender page using HTTPS. Otherwise, you'll only be able to test using `localhost`.
