### ISSUE TITLE
Link is being played on VLC but cannot be played with Clappr

### ISSUE THREAD

**Issue by AmrElbalshy** [clappr/clappr#1827]
Hi,
I can play this m3u8 with VLC but cannot be played usin Clappr:
http://80.80.160.168/live/5/500000/live.m3u8

"my player:

<script>
    
 
var playerElement = document.getElementById("player");

var player = new Clappr.Player({
	 width: "100%",
	height: "480",
	plugins: {
          'core': [LevelSelector]
        },
});

player.attachTo(playerElement);
player.load({source: 'http://80.80.160.168/live/5/500000/live.m3u8'});

player.play();

  </script>

**Comment by kslimani** [comment]
It is likely a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue.

**Comment by towerz** [comment]
@AmrElbalshy indeed, this is a CORS related issue.

VLC does not have this problem since it doesn't actually require compliancy with CORS policies, unlike running players in a Browser environment.

Testing your URL in the [Clappr demo page](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovLzgwLjgwLjE2MC4xNjgvbGl2ZS81LzUwMDAwMC9saXZlLm0zdTgnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBhdXRvUGxheTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=) I had the following errors:

On Chrome:
```
Access to XMLHttpRequest at 'http://80.80.160.168/live/5/500000/live.m3u8' from origin 'http://clappr.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

On Firefox:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://80.80.160.168/live/5/500000/live.m3u8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
