### ISSUE TITLE
UI customization

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1846]
I'm sorry to write this question on issues, but I can't find any other place to do that.
How can I customize the play button and any other UI elements?
Many thanks!

**Comment by towerz** [comment]
Hi, @DanieleSuppo73. Right now, we don't have the UI elements separate from the `MediaControl` plugin. So the way to do that right now is extending it or replacing with your own controls.

Extending would be the easiest way because you would be able to reuse the template and only replace the UI elements or CSS styles as needed.

In a future release (probably this month) we'll have the UI elements as separate plugins, so you would only need to override the elements you want to replace or change instead of overriding the entire UI.

**Comment by ChristopheBougere** [comment]
I'm just discovering clappr and I have the same need, I can't wait for the new release that makes it easy to customize UI 👌

**Comment by kslimani** [comment]
Maybe make some non-breaking changes, for example expose all svg icons in a class or a simple plain object in the Utils module (Utils.SVG ?) and use Utils module in media_control, favicon, poster, closed_captions and arror_screen plugins.

This simple change could allow developper to override svg with customs. For example :

```javascript
Clappr.Utils.SVG.play = 'raw_custom_svg_import'; // before create Clappr instance
```

It is pretty simple changes, i can submit a PR proposition if required.
