### ISSUE TITLE
m4v on Clappr player html code

### ISSUE THREAD

**Issue by AmrElbalshy** [clappr/clappr#1849]
Hi,
I would like to run m4v video on my site, what should be the html code of Clappr (how to customize it)?

**Comment by leandromoreira** [comment]
You can see [how to use Clappr at the main page](https://github.com/clappr/clappr#using-the-player) and you can inspire by the [demo page](http://clappr.io/demo/)

**Comment by AmrElbalshy** [comment]
![Capture](https://user-images.githubusercontent.com/48377763/64500614-3406f080-d2be-11e9-9014-21f4f9950e17.PNG)

I got this after inserting m4v url

**Comment by leandromoreira** [comment]
@AmrElbalshy I don't think it's possible for clappr to play directly the `m4v` file directly, usually these files are from `MPEG dash` package format and they require a `header` so in order to play these files you should point to the `.mpd` manifest file OR (if `m4v` is a complete ISO format file) rename it to `mp4` and try it again.
