### ISSUE TITLE
Impossible to play with Clappr?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1855]
Is there any way to play this stream with Clappr?
https://livehlsdai-i.akamaihd.net/hls/live/571640/telecinco/bitrate_4.m3u8

it uses a key: https://gatekeeper.mediaset.es/key/telecinco/akamai

**Comment by leandromoreira** [comment]
@hijuuijj it's because it returns a `403`

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/55913/65059061-affed980-d94b-11e9-9200-356c3bbd37ba.png">

You [can see it here](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9saXZlaGxzZGFpLWkuYWthbWFpaGQubmV0L2hscy9saXZlLzU3MTY0MC90ZWxlY2luY28vYml0cmF0ZV80Lm0zdTgnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=).

**Comment by hijuuijj** [comment]
I thought there was some trick :(
