### ISSUE TITLE
Fullscreen error on double click

### ISSUE THREAD

**Issue by fabioricali** [clappr/clappr#1860]
**Browser**: Chrome 77.0.3865.90 

**OS**: Windows 10

**Clappr Version**: 0.3.9

**Steps to reproduce**:

* first step
Open console then double click on player:

Uncaught (in promise) TypeError: fullscreen error

Did you try to reproduce this issue at http://cdn.clappr.io/

**Comment by kslimani** [comment]
Thank you @fabioricali , i confirm the issue.

WIth Chrome 77.0.3865.90, double-clicking player switch player to fullscreen mode and trigger an "Uncaught (promise) TypeError: fullscreen error"

It seems not to be a critical issue because fullscreen feature still works. (*may* be a Chrome temporary issue).

**Comment by towerz** [comment]
@fabioricali as @kslimani answered it seems to be a Chrome issue. I checked the event handler chain and the fullscreen call is being done directly on the event handler stack.

I'll close this issue for now since the feature is working and the problem seems to be related directly to Chrome (and Chromium-based browsers). If the problem persists or the feature breaks we can revisit it.

**Comment by towerz** [comment]
@kslimani just so you know, we're splitting the Clappr codebase into separate projects: one with the [core components](https://github.com/clappr/clappr-core/) and another with the [main plugins](https://github.com/clappr/clappr-plugins/), which will be converted into a monorepo.

The playbacks are being split into their own projects as well: [hlsjs-playback](https://github.com/clappr/hlsjs-playback/), [flashls-playback](https://github.com/clappr/flashls-playback/) and [flash-playback](https://github.com/clappr/flash-playback).

This will allow us to release more fine-grained package updates, and allow us to better keep track of issues and pull requests. Another upside from this is that users can build their own versions of Clappr without being burdened with unused plugins.

**Comment by joaopaulovieira** [comment]
Hi! I opened a [PR on @clappr/core](https://github.com/clappr/clappr-core/pull/38) which I think solves this issue. Feel free to discuss the solution on the PR (:
