### ISSUE TITLE
How to center full screen mode

### ISSUE THREAD

**Issue by fish101022** [clappr/clappr#1881]
Is there a way to get full screen mode to center in the screen rather than anchor to the top left? It looks quite awkward that way. I feel like it should be a fairly easy modification but I've combed through the code and couldn't find it anywhere. Would be grateful if someone more knowledgeable could lend a hand.

**Comment by kslimani** [comment]
@fish101022 i am not sure to understand your issue; To my knowledge, the fullscreen mode _(when requested by Javascript)_ is handled by the browser.

Could you please elaborate on the "top left" ? _(maybe providing a screenshot ?)_

**Comment by fish101022** [comment]
I've put a screenshot in here. I'm wondering if this is a result of Wordpress or Sitebuilder as I've tried to copy in the code exactly from the sample video provided on here and it does the same thing, where in the sample it works correctly as full screen 

![Sample_SS](https://user-images.githubusercontent.com/50544656/70209677-433df300-1774-11ea-9b7f-613f1ba7c2b8.jpg)


Sample I'm referring to: http://cdn.clappr.io/?src=http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

**Comment by kslimani** [comment]
Which operating system and browser versions are you using ?

Also, check if your player is build/loaded into an iframe; if this is the case, ensure that iframe element has the `allowfullscreen` attribute set to true.

This seems to be a coding issue rather than the player itself _(using a site editor may sometimes lead to strange results)_. To help you further, it may require you to share a page, allowing us to debug the issue.
