### ISSUE TITLE
PLAYER_READY event does not fire up

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1902]
**What do you want to do with Clappr?**

I'd like to know when a video is loaded and ready to play.
I'm successfully using all others Clappr events (PLAYER_PLAY, PLAYER_ENDED, PLAYER_SEEK, PLAYER_PAUSE, ...)
but "PLAYER_READY" does not work.

Any help would be much appreciated!
Thank-you

**What have you tried so far?**

var player;
player = new Clappr.Player({
            source: "some url for the video",
            width: "100%",
            height: "100%",
            parentId: "#player",
 });

player.listenTo(player, Clappr.Events.PLAYER_READY, () => {
            console.log("Video ready");
});

**Comment by kslimani** [comment]
@DanieleSuppo73 your issue here may be because the player is ready __before__ your listener is added to the player.

Two solutions comes to my mind. The first is to create player instance without parent selector, then bind the event then use the attachTo method.

Try this code at [Clappr demo site](http://clappr.io/demo/) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

// Add event listener BEFORE attaching player to document
player.listenTo(player, Clappr.Events.PLAYER_READY, () => {
  console.log("Video ready");
});

player.attachTo(playerElement);
```

The second solution is to use the `events` player option :
(see also [Events API](https://github.com/clappr/clappr/blob/dev/doc/API_EVENTS.md) documentation)

```javascript
var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  parentId: '#player-wrapper',
  events: {
    onReady: function() {
      console.log('Video ready');
    },
  },
  height: 360,
  width: 640
});
```

**Comment by DanieleSuppo73** [comment]
Many thanks  @klsimani,
the 2nd solution would seem to be the perfect one,
but sometimes it's not fired!
