### ISSUE TITLE
Video not playing without unsafe-eval on CSP implementation in Angular JS

### ISSUE THREAD

**Issue by vigneshwarrk** [clappr/clappr#1905]
Hello team,

In our application, we are using the clappr video lib which is quite simple and easy to implement. Currently, we are facing one problem with the lib after the implementation of **CSP(without unsafe-eval)** in our application. Please find the screenshot of the error. The issue is after clicking on the play button it's not playing the video instead it's giving this error which we couldn't take it further.

![2020-03-01](https://user-images.githubusercontent.com/50876320/75650705-bde7b300-5c7c-11ea-97b9-0f4401f49359.png)

![2020-03-01 (1)](https://user-images.githubusercontent.com/50876320/75650709-c213d080-5c7c-11ea-97b2-34493048d92d.png)

**Note:** if we mentioned unsafe-eval in the CSP header then the videos are playing. We want that to happen without unsafe-eval in the header

Do you guys have any solution for this?

Looking forward to your reply.

Thanks in advance

Cheers Team.

**Comment by kslimani** [comment]
Are you using Clappr from a CDN or it is hosted on your domain (or bundled in your application ?) ?

**Comment by vigneshwarrk** [comment]
@kslimani : thanks for your reply

 it's not CDN link. We are pointing clappr lib from our file server.

![](https://lh3.googleusercontent.com/-qry1_XYOm98/XlzsX6ifXoI/AAAAAAAABAk/e60FQBLiF38pl2pnyhF0m_C917Haig-awCK8BGAsYHg/s0/2020-03-02.png)

**Comment by kslimani** [comment]
I am not an expert with content security policy, but in your screenshot, the `'unsafe-eval'` keyword is only set for `font-src` directive. Maybe you need to also add this keyword to `script-src` directive ?

**Comment by vigneshwarrk** [comment]
Our requirement is not to set the unsafe-eval in the script-src directive for security purposes. CSP implementation is mainly to avoid external XSS attacks.  For styles, fonts ect., we set unsafe-eval because there won't be much impact but in the script-src directive, we have too.

It will be great if I get a solution to this issue

Cheers

**Comment by kslimani** [comment]
Well, if i am not wrong Clappr internal template engine is using eval _(Function constructor)_, this may be the reason you get that error. Nothing comes to my mind yet to fix this issue.

**Comment by vigneshwarrk** [comment]
@kslimani : Thanks for your response. It will be really great if we get that fix in the upcoming version. It will be very much helpful for our application.

Looking forward to this fix.

Cheers :)

**Comment by joaopaulovieira** [comment]
Hi @vigneshwarrk , sorry for the delayed response. As kslimani said, the [template](https://github.com/clappr/clappr-core/blob/master/src/base/template.js#L98) approach used by the project is the cause of your problem. You can check, our approach is the same as the underscore. I'm read more about this issue on the underscore and apparently, is not one main issue to the project so it's not fixed by the underscore guys. You can check the discussion about in the issues below:

* https://github.com/jashkenas/underscore/issues/906
* https://github.com/jashkenas/underscore/issues/2273

One PR to fix this behavior is super welcome (implementing another approach to handle with templates or fixing the actual).

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
