### ISSUE TITLE
How to force synthetic HLS on Safari?

### ISSUE THREAD

**Issue by blordpluto** [clappr/clappr#1923]
I need access to the more granular events of HLS  like `Clappr.HLS.HLSJS.Events.FRAG_LOADING`,  and `Clappr.HLS.HLSJS.Events.FRAG_CHANGED` that Safari's native implementation doesn't expose. In other words I want to ignore the native implementation. Can you point me to how I might approach this? Ideally it could be set by a boolean in the config called something like `overrideNative`. Thanks in advance for any help, and a great project.

**Comment by kslimani** [comment]
Clappr player is internally using the library [hls.js](https://github.com/video-dev/hls.js) to play HLS source using the [hls playback](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js). _(which extend the html5 video playback)_
See also the hls.js [browser compatibility list](https://github.com/video-dev/hls.js/#compatibility).

When hls.js is not supported by the browser, it fallback on the [html5 video playback](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js).

You could force the hls playback to be loaded on Safari (or any) browser but it may simply not work because not supported (again see hls.js compatibility documentation).

In other word, if the hls event you need is not exposed by native html video element there is no way (AFAIK) to access it.
