### ISSUE TITLE
API Filter is not working

### ISSUE THREAD

**Issue by kmlhsn** [clappr/clappr#1986]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Firefox 83.0

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows 10
**Clappr Version**: 0.3.8

**Steps to reproduce**:

1. Go to "http://clappr.io/"
2. Click on "hamburger menu"
3. Click on "Documentation"
API Filter not working. it can not filter API from List. and Text box should have "Search button".
![image](https://user-images.githubusercontent.com/32615215/100774086-e844e780-342b-11eb-9129-7f9e523b63ea.png)

Did you try to reproduce this issue at http://cdn.clappr.io/

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

**Comment by nandy-andy** [comment]
This is because when you click "Documentation" item in the menu you'll open the docs page over https: https://clappr.github.io/ and then one of the dependencies (YUI 3.9.1) is blocked in Google Chrome because it's requested over http:
<img width="1278" alt="Screenshot 2021-12-02 at 23 24 51" src="https://user-images.githubusercontent.com/1662451/144513053-8429a4c3-1c49-437f-ad43-0194a62eee69.png">

When you open the clappr docs page without the https: http://clappr.github.io/ the dependency is loaded properly and the search works.

Unfortunately, it seems that the assets can't be served via https:
* https://yui.yahooapis.com/3.9.1/build/cssgrids/cssgrids-min.css
* https://yui.yahooapis.com/combo?3.9.1/build/yui/yui-min.js

Therefore, I can think of 3 possible solutions:
1. Change the link to docs, so it does always lead to the plain http version (poor idea).
2. Download the assets, add to the clappr's page files and load them from the same URL as the docs page (I'm not sure if the license allows it).
3. Find a CDN that serves the assets over https and replace the current links with a new CDN.
