### ISSUE TITLE
Mediator alternative

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1990]
i'm adapting my youtube playback to clappr@0.4.2. I used to use Mediator to find out when the player size changed.
Do I have a chance to listen to Events.CORE_RESIZE from the playback?

**Comment by kslimani** [comment]
Since Mediator has been removed, i am not sure you can still use this trick anymore. The playback base component is (if i remember correctly) unaware of core.

A possible workaround (but require some work) may be to refactor your plugin as an ui core plugin and manage the custom YT playback instance internally. For example, take a look at the [chromecast plugin](https://github.com/clappr/clappr-chromecast-plugin).

**Comment by leticiafernandes** [comment]
Hi @sapolio, as @kslimani said the only way to listen to this event is through Core. We will close this issue due to inactivity.
