### ISSUE TITLE
npm is outdated!!

### ISSUE THREAD

**Issue by jvsdr** [clappr/clappr#2038]
Hey guys,

The npm repository is outdated! Please update to last version. Currently the last version in npm is **0.3.13** and today the last version I guess is **0.4.6*

![Screenshot_1](https://user-images.githubusercontent.com/10999602/136887488-051ed94d-453b-4be3-802a-25462855dcdb.png)
*

https://www.npmjs.com/package/clappr

**Comment by kslimani** [comment]
This is not a bug :)

This npm repository is for the 0.3 branch.

Because of the [many breaking changes](https://github.com/clappr/clappr/releases/tag/0.4.0), it was decided to put the 0.4 branch into another npm package : https://www.npmjs.com/package/@clappr/player

Please also, take a look at [readme file](https://github.com/clappr/clappr/blob/dev/README.md).

**Comment by jvsdr** [comment]
> This is not a bug :)
> 
> This npm repository is for the 0.3 branch.
> 
> Because of the [many breaking changes](https://github.com/clappr/clappr/releases/tag/0.4.0), it was decided to put the 0.4 branch into another npm package : https://www.npmjs.com/package/@clappr/player
> 
> Please also, take a look at [readme file](https://github.com/clappr/clappr/blob/dev/README.md).

Ohh thank you for info mate! I didn't know about it 😃
