### ISSUE TITLE
support for YouTube videos

### ISSUE THREAD

**Issue by JahlomP** [clappr/clappr#269]
I suggest support be made for youtube videos too.

**Comment by sfia-andreidaniel** [comment]
Vote up

**Comment by towerz** [comment]
@JahlomP @sfia-andreidaniel It's being implemented as an external playback plugin, on [towerz/clappr-youtube-playback] (http://github.com/towerz/clappr-youtube-playback). If you think there's anything that should be implemented on the playback, you are welcome to contribute.

I'm closing this issue now, since the plugin development is on a separate project.

**Comment by zetatv** [comment]
Hola, he estado testeando el pluggin y el problema qu tiene es que al usar resoluciones mayores a 640x360, el video no se adapta, inclusive cuando uno pone el video en pantalla completa, me gustaria saber en que estoy fallando.
@towerz 
Hello, I've been testing the plugin and the problem you have is that using resolutions higher than 640x360, the video does not fit, even when you put the video in full screen, I would like to know I'm failing.

**Comment by towerz** [comment]
@zetatv the plugin actually is just a proof of concept, it's not really under active development. I try to keep it compatible with the latest version of clappr, but seemingly it broke due to either a clappr or youtube api update.

I'll open an issue to check what's wrong with it. Thanks for bringing this up.
