### ISSUE TITLE
HLS playback is not working in embeds (jsfiddle)

### ISSUE THREAD

**Issue by whadar** [clappr/clappr#388]
http://jsfiddle.net/cuy8rv3k/

I get
 Uncaught TypeError: undefined is not a functionhls.js:80 setFlashSettingshls.js:204 firstPlayhls.js:118 playcontainer.js:130 playposter.js:95 clickedzepto.min.js:2 i.split.forEach.s.proxy

on
    this.el.globoPlayerSetflushLiveURLCache(this.flushLiveURLCache)

mp4 file works fine

**Comment by stjernstrom** [comment]
This jsfiddle work in Safari (OS X) and Chrome on my Xperia Android. First time In Chrome (osx) i got a "Cross-Origin Resource Sharing policy" error and after that i get the same error as you

Can it be that flash fallback need some cross origin policies to work?

**Comment by towerz** [comment]
@stjernstrom The jsfiddle will work in any browser that uses the html5_video playback for HLS content.

@whadar The problem seems to be with the way jsfiddle renders the html snippet. It uses a sandboxed iframe, which blocks execution of plugins. This makes HLS playback to fail because the SWF is not loaded. In fact, no request to the SWF file is made at all.

We'll check if there's a way to detect if the player is loaded in a sandboxed environment to prevent these errors from occurring, but I think we won't be able to load the HLS playback correctly anyway.

**Comment by towerz** [comment]
Since the iframe sandbox environment does not allow embedding flash, the flash based HLS playback won't work. There's no solution available to prevent this from happening, aside from loading the HTML5 playback (supported only on Safari and mobile browsers).

Closing issue for now, can't fix this for the flash playback.

**Comment by whadar** [comment]
zeroclipboad had similar issues:
https://github.com/zeroclipboard/zeroclipboard/issues/511
