### ISSUE TITLE
Full screen on double click (touch)

### ISSUE THREAD

**Issue by btecu** [clappr/clappr#391]
It's very difficult to go to full screen mode on mobile devices. It would be great if you could double click or double touch the player and it would go into full screen mode.

**Comment by irongomme** [comment]
I agree, it could be nice ! 
Maybe, it could be done in the same time of this issue : #336

**Comment by flavioribeiro** [comment]
hey @btecu and @irongomme, we didn't had much time to look at the behavior of clappr on mobile phones yet. All contributions on this matter are welcome!

**Comment by irongomme** [comment]
What about adding libs to trigger mobile gesture events ?

Because click or dbleClick won't be enough to cover all devices ...

**Comment by irongomme** [comment]
I'm working on it, and in my opinion, this will be better to let people choose the action on each events ! Because this is quite easy to listen on player container event and trigger fullscreen on double click or double tap for example. 

What do you think all about adding a light library like jquery.finger (it's about 0.5k) and covers main mobile gestures (tap, doubleTap, drag, press, flick) ?

**Comment by irongomme** [comment]
Finaly module zepto-touch which is allready included do the job , and finaly fullscreen on doubletap should be a default behavior !

**Comment by towerz** [comment]
@irongomme Thanks for implementing this. We're still lacking support for touch gestures, but it's something we will start focusing soon. Probably after releasing version 0.1.0 (I'll set a milestone after releasing 0.0.115 with current bugfixes).

I think we can close this issue now. If there's something else you need to implement with touch interfaces please open a new issue.
