### ISSUE TITLE
Media controls not showing on Safari (8.0.3)

### ISSUE THREAD

**Issue by brocaar** [clappr/clappr#392]
Most of the times, I can't see the media controls (when starting the video) when using Safari (8.0.3, OS X 10.10.2). Sometimes it shows up after refreshing many times, but most of the time it doesn't. Same code works fine on Chrome.

```html
<html>
 <head>
    <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
 </head>
 <body>
   <div id="player"></div>
   <script type="text/javascript">
    var player = new Clappr.Player({
      source: "http://hls.server/playlist.m3u8",
      parentId: "#player"
    });
   </script>
 </body>
</html>
```

**Comment by towerz** [comment]
@brocaar Could you please check whether this bug persist on your tests? I cannot reproduce this error on http://cdn.clappr.io using an up to date Safari (8.0.5, OS X 10.10.3).

**Comment by brocaar** [comment]
Yes, I'm still able to reproduce it, but only when playing a HLS live stream.

**Comment by Facecast** [comment]
Same problem i have.

**Comment by towerz** [comment]
@brocaar @Facecast I believe the problem is that Safari is not sending pointer events to the mediaControl instance, thus making it not visible. After forcing it to re-render or trying to access the element via the console, the mediaControl starts showing on mouseover, but it's still missing pointer events.
I'll post updates as I find out more about this issue.

**Comment by towerz** [comment]
I really seems to be a bug on Safari. After I updated to a later version (8.0.6) it doesn't happen anymore.

Please reopen if you run into this problem again.
