### ISSUE TITLE
Bouncing spinner when loop is enabled

### ISSUE THREAD

**Issue by LeonardoCardoso** [clappr/clappr#413]
If loop is enabled, the three bouncing ball spinner appears.
It would be more natural if it didn't show up.

**Comment by LeonardoCardoso** [comment]
I noticed that the video is loaded again from its source on looping. Maybe caching the video would solve this. I'm closing this issue.

**Comment by LeonardoCardoso** [comment]
I just noticed that the video is loaded again from its source. That's why the loading shows up. Maybe caching the video might solve this.

**Comment by towerz** [comment]
@LeonardoCardoso Most of the time the spinner is shown due to the start of the video being removed from the buffer, due to browser buffering policies. The video is not actually loaded from source, only the loop property is set on the element.

We cannot control whether to keep the first portion of the video on buffer, but we can delay displaying the buffering indicator for a small interval (100-300 ms). This will prevent the loading indicator to blink when the video is looped around.

Please let me know if this change solves your problem.

**Comment by LeonardoCardoso** [comment]
Tested. Nice!
