### ISSUE TITLE
Playing false HLS and other http streams?

### ISSUE THREAD

**Issue by princ007** [clappr/clappr#434]
Hello,

is this possible that with an external plugin the player can play the following URLs?
For example:
http://200.76.77.237/LIVE/H01/CANAL371/PROFILE03.m3u8? (this is not real HLS, but I don't know which extension is)
or
http://5.189.144.85:1935/live/orf1 (http stream without extension m3u8)

Thanks for the answer.

**Comment by towerz** [comment]
Hi @princ007, I'm not sure why you refer to the m3u8 playlist as false HLS. Apart from the playlist missing the `EXT-X-ENDLIST` (doesn't seem to be a live stream, so the end tag is required) and the wrong `Content-type` header (`text-plain`), it appears to be valid. I couldn't test it because of a status 403 requesting the `crossdomain.xml`, but it should work ok with no plugins needed. Please try to add cdn.clappr.io to the list of allowed domains in `crossdomain.xml`. This way you can use the [test page](http://cdn.clappr.io) to check if your stream will work.

The second URL could require a plugin to play, but I cannot identify what it the stream format.
