### ISSUE TITLE
Clappr reports bufferstatefull event after returning from paused mode

### ISSUE THREAD

**Issue by shaharmor** [clappr/clappr#448]
Is this supposed to happen?

**Comment by towerz** [comment]
@shaharmor What kind of source are you using? Is it a mp4 or HLS stream?

**Comment by shaharmor** [comment]
Hls

**Comment by towerz** [comment]
@shaharmor Indeed, the HLS playback triggers a bufferfull event after changing to PLAYING state, whether it's buffering or not. I believe this was done to workaround an issue on a older version of our flashls implementation, but it seems to be unnecessary right now. 

It won't cause any unexpected behavior as well, because changing to a PLAYING state implies that the player is not in a buffering state.

**Comment by shaharmor** [comment]
Can it be disabled? We are using the bufferfull event to measure buffers
and this is (obviously) not a buffer so that event is a bug.

**Comment by towerz** [comment]
It will be removed in the next version, we just need to run some tests to make sure it won't introduce any weird behavior.
