### ISSUE TITLE
prefetch poster with HLS?

### ISSUE THREAD

**Issue by chovy** [clappr/clappr#474]
***1 Upvote*** On safari, the `<video>` tag will prefetch the poster of the stream. Is there anyway to get this same feature with the Clappr HLS plugin?

**Comment by towerz** [comment]
@chovy I'm not sure what do you mean by prefetching the poster of the stream. The poster image used by Clappr is actually provided by the poster plugin. Could you elaborate on this?

**Comment by chriswiggins** [comment]
I think what he means is that Safari generally loads the latest .ts file and decodes it, providing a "thumbnail" of the video at its current state. Surely there's a way to do this but it might be about playing the HLS player and then pausing it as soon as the first frame is displayed. Otherwise maybe theres an option in Flashls?

**Comment by chovy** [comment]
yes, that's exactly what I mean. Its a nice UX to have the poster instead of a made up banner or nothing.

**Comment by whadar** [comment]
+1 

That would be cool and very useful for live. Did anyone see something like that in Javascript?

**Comment by flavioribeiro** [comment]
I'm not sure if it's possible to get the first frame of the TS using hlsjs and canvas, but maybe [this demo](http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2014/12/html5-video-article-demos/thumbnails-demo.html) from http://www.sitepoint.com/html5-video-fragments-captions-dynamic-thumbnails/ can point to the right direction.
