### ISSUE TITLE
getting cross domain error on hls stream

### ISSUE THREAD

**Issue by chovy** [clappr/clappr#476]
I've loading a remote HLS stream, which works fine in VLC and native Safari `<video>` tag, but in Clappr w/ HLS plugin (chrome) I get a cross domain error. Apparently the server is recognizing it being loaded off my domain in Clappr, but not when I use the native Safari video tag.

**Comment by towerz** [comment]
@chovy In order to load cross domain content using the flash plugin, it must be authorized through a `crossdomain.xml` spec file, otherwise the plugin fails to load the content. Using Safari there's no need for it, since the HLS stream is loaded directly by the browser. This behavior is correct, it's not an error.
