### ISSUE TITLE
Live switching between RTMP and HLS

### ISSUE THREAD

**Issue by chriswiggins** [clappr/clappr#478]
Hi Clappr team,

Really like the Clappr player and have been conducting some tests with it so far. 

I have a question about whether it's possible to switch from RTMP to HLS to perform timeshifting? Currently we're delivering a 1-hour moving HLS window however this introduces significant lag when watching a live stream. Our hope is to use RTMP for live streaming and to switch back to HLS when a user wants to "rewind" the live stream. Ideally this would all happen behind the scenes such that the user wouldn't know it was happening. 

Is this possible at the moment? If not, what do I need to do to go about writing code for this to work? Point me in the right direction and I'll see what I can develop :-)

Thanks
Chris

**Comment by towerz** [comment]
@chriswiggins It's possible, but since you need to switch between two different types of playback and tricking the media control that it's possible to seek back on the live stream, you should create a playback proxy.

Just create a playback that informs the 1-hour window for seeking back, but keeps showing the RTMP playback for the live stream. When the user seeks back, you just need to swap from the RTMP playback to your HLS and set the current position properly.

I believe @flavioribeiro have already started helping you with this, but if you have any doubts, please let me know.

**Comment by chriswiggins** [comment]
Hey @towerz , I've already started heavy development on this and initial results are good. Take a look at https://github.com/securogroup/clappr-rtmp-hls and let me know what you think. I'm also making a fair few changes to the RTMP plugin to support changing scaling mode, amongst a few other things so expect a few pull requests against that :-)

Are you normally available on Gitter? I'm signed in most days so would be keen to chat if you have the time

**Comment by chriswiggins** [comment]
I'm going to close this, and hopefully see you guys over in securogroup/clappr-rtmp-hls :-)

**Comment by towerz** [comment]
I'm not usually online on Gitter, but I'll try to sign in and try to help you with any questions.
