### ISSUE TITLE
IE11 crashes with mp4

### ISSUE THREAD

**Issue by VladimirVSgh** [clappr/clappr#495]
IE 11 crashes with Clappr often. This problem is actual not only for HLS streams, but for mp4 files too (http://clips.vorwaerts-gmbh.de/VfE_html5.mp4). Standard video tag works without any problems.

IE11 crashes after start of playing in 0.5 sec. If IE don't crash at startup, it works OK later.
Before crash Debug shows:
playback:bufferfull html5_video
container:state:bufferfull Container
container:mediacontrol:enable

Chrome and Firefox are OK.

**Comment by stanogurnik** [comment]
I must confirm this behaviour, we were playing with clappr recently trying to fix this issue with IE (all versions).  Funny thing about this is that it crashes IE only for first time, after refresh it works almost beautifully. Because of crash of ie is almost impossible to find spot where it crashes , but we were able ti identifiy it crashes after Events.PLAYBACK_READY is fired from playback. When uncommenting this , IE wont crash.

**Comment by towerz** [comment]
@VladimirVSgh @stanogurnik could you please test whether the change in 83740f32d057b88bb3eeefa8e1d9fe78b05ae6ea fixed this behavior? I could not reproduce this behavior with MP4 files, but I believe the crash with HLS streams doesn't occur anymore after this fix.
