### ISSUE TITLE
Plugin architecture help

### ISSUE THREAD

**Issue by iongion** [clappr/clappr#497]
first: **clappr is awesome !!!**

Now, is there a formal documentation on how to build plugins ?
- in my architecture, videos are provided by url hashes `#vabcd1000-m4` - and I have a convention for this hash that decodes it to an url and becomes: http://my.video-vabc.com/users/1000/video.mp4
- another situation is with custom video playlists - my playlists are yaml based - how can I build a plugin that knows how to play a playlist(such as, choose the first item in the beggining, play next after prev finished playing, loop if at last) ?

My questions are not how to actually build, but what is the architecture for this ? What hooks do I have to override to able to have a "source" provider in clappr, is it even possible?
I could build them as standalone libraries, but I would really like to follow the idiomatic **clappr** way of doing plugins that I am sure all of you met many times

**Comment by towerz** [comment]
Thanks @iongion! We are still lacking most of the documentation, due to our reduced team, but there's some work in progress in that direction. I believe we will have the documentation/tutorials/blog pretty soon.

I'll try to answer your questions and maybe shed some light with how you could create plugins that can solve your problem.

We use Clappr as the base of our player at globo.com, and face a similar issue you have. Essentially, our player uses ids that reference the videos in our platform, and we created a playback plugin that handles all this logic and then instantiates the actual playback to be played. This results in a playback that acts as a proxy for the underlying playback, but handling all the api calls and controlling the playback states so the interface keeps waiting until the video starts.

Every playback that is loaded in Clappr declares a `canPlay` method that returns whether it knows how to play a given source (usually a string):
```javascript
var MyPlayback = Clappr.Playback.extend({
  // ...
});
MyPlayback.canPlay = function(source) { return true };
```
This way you can add support for new formats ("source" providers) just adding them to the plugin list when instantiating Clappr:
```javascript
var player = new Clappr.Player({
  plugins: { playback: [MyPlayback] },
  // ...
});
```
Clappr gives priority to external plugins to override behaviors more easily.

For the second question, you could either create a core plugin or another playback. Plugins in Clappr are scoped: core plugins have access to the whole player state, container plugins are constrained to a single container (where the playback is rendered) and playback plugins are "source" providers.

If you decide to go through the core plugin route, you just need to parse your playlist, instantiate a container for a given source, and set it as the current. Then you just listen for the CONTAINER_ENDED event and then play the next:
```javascript
var MyPlaylistPlugin = Clappr.CorePlugin.extend({
  // ...
  bindEvents: function() {
    this.listenTo(this.core.getCurrentContainer(), Clappr.Events.CONTAINER_ENDED, this.loadNextVideo);
    // ...
  },
  loadNextVideo: function() {
    var container = // ...
    this.core.mediaControl.setContainer(container);
  }
});
```
The second route is like the first one, but instead of replacing containers, you just create your playback proxy and switch the underlying playbacks after receiving a PLAYBACK_ENDED event. This option has the advantage of adding the playlist as a "source", but you cannot change the media control behavior.

Perhaps a mix of both the solutions could be ideal for you, but the simplest is just to create a core plugin to control the sequence. Since Clappr creates multiple containers (each with its own playback) if you use the `sources` parameter (as an array) instead of `source`, you could use this to create all containers for your playlist and just swap them as needed. Your plugin could parse the playlist, set the sources on `core.options.sources` and use `core.createContainers` to instantiate all containers for you. Then it's just a matter of controlling the playback state for the containers as mentioned before.

**Comment by towerz** [comment]
Just to add a bit more code, here's a sample for a custom playback proxy supporting a hash like the one you mentioned:
```javascript
var MyPlayback = Clappr.Playback.extend({
  constructor: function(options) {
    this.options = options
    // ...
  },
  // ...
  // create underlying playback given the actual url
  findPlaybackPlugin: function(source) {
    return _.find(PlayerInfo.playbackPlugins, function(p) { return p.canPlay(source.toString()) }.bind(this), this);
  },
  play: function() {
    if (!this._playback) {
      // Your hash -> url logic
      var url = this.hashToUrl(this.options.src);
      var playback = this.findPlaybackPlugin(url);
      var options = _.extend({}, this.options, { src: url, autoPlay: false });
      this._playback = new playback(options);
    	this.bindPlaybackEvents();
    } else {
      this._playback.play();
    }
  },
  // forward playback events
  bindPlaybackEvents: function() {
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_PROGRESS, this.progress)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_TIMEUPDATE, this.timeupdate)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_BUFFERING, this.buffering)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_BUFFERFULL, this.bufferfull)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_SETTINGSUPDATE, this.settingsupdate)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_LOADEDMETADATA, this.loadedmetadata)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_ENDED, this.ended)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_PLAY, this.playing)
    this.listenTo(this.playback, Clappr.Events.PLAYBACK_PAUSE, this.paused)
    this.listenToOnce(this.playback, Clappr.Events.PLAYBACK_READY, function() {
      this.play();
      this.bufferfull();
      this.settingsupdate();
      this.ready();
      // ...
    }.bind(this));
  },
  // Other methods ...
});
// This is how you declare whether your playback can play a given source
MyPlayback.canPlay = function(source) {
  return /^#[a-z0-9-]+$/.test(source)
};
```

**Comment by towerz** [comment]
And here's a sample for a mixed playback/core plugin solution for implementing a playlist:
```javascript
var MyPlaylistPlayback = Clappr.Playback.extend({
  getPlaybackType: function() { return "playlist" }
});
MyPlaylistPlayback.canPlay = function(source) {
  /PLAYLIST_PATTERN/.match(source);
}
  
var MyPlaylistPlugin = Clappr.CorePlugin.extend({
  constructor: function(core) {
    this.core = core;
    if (this.core.getPlaybackType() === "playlist") {
      this.loadPlaylist()
    }
  },
  loadPlaylist: function() {
    // load your playlist
    // ...
    this.core.options.sources = [list, of, sources];
    this.core.getCurrentContainer.destroy();
    this.core.createContainers(this.core.options);
    this.core.mediaControl.setContainer(this.core.containers[0]); // select first item on playlist
    this.bindEvents();
  },
  bindEvents: function() {
    this.listenTo(this.core.getCurrentContainer(), Clappr.Events.CONTAINER_ENDED, this.loadNextVideo);
  }
});
```
As I mentioned before, you just need to add those to the plugin list when instantiating the player:
```javascript
var player = new Clappr.Player({
  source: "PLAYLIST_PATTERN",
  plugins: {core:[MyPlaylistPlugin], playback: [MyPlaylistPlayback]},
  // ...
});
```

**Comment by towerz** [comment]
Perhaps your implementation will be a bit more complicated than this, but I think it's a good start.

Please let me know if you have further questions.

**Comment by iongion** [comment]
In the current clappr - PlayerInfo.playbackPlugins is empty, where did the plugin registry go ?

**Comment by iongion** [comment]
For the most recent clappr `latest` I have managed to arrive here:

```
/* eslint-disable no-console */

import { Playback } from 'clappr';

const expected = 'http://media-euw1.keemotion.com/shared-playlists/378/ee14.m3u8';

const PLAYER_DOMAINS = [
  '//player.keecast.tv',
  '//player.keemotion.com',
];

export default class KeemotionVideoHashSource extends Playback {

  get name() { return 'keemotion_video_hash_source'; }

  constructor(options) {
    super(options);
    this.options = options;
  }

  findPlaybackPlugin(source) {
    const playbackPlugins = this.options.loader.playbackPlugins;
    for (let i = 0; i < playbackPlugins.length; i++) {
      const PlaybackPluginClass = playbackPlugins[i];
      if (PlaybackPluginClass.canPlay(source)) {
        return PlaybackPluginClass;
      }
    }
    return null;
  }

  hashToUrl(hash) {
    // TODO: write decoder
    return expected;
  }

  play() {
    if (!this._playback) {
      const decodedSourceURL = this.hashToUrl(this.options.src);
      const PlaybackPluginClass = this.findPlaybackPlugin(decodedSourceURL);
      if (PlaybackPluginClass) {
        this.options.src = decodedSourceURL;
        console.debug('constructing playback plugin instance', this.options);
        this._playback = new PlaybackPluginClass(this.options);
        this._playback.play();
      }
    } else {
      this._playback.play();
    }
  }

}

KeemotionVideoHashSource.canPlay = (source) => {
  // should return true for the supported media source
  const schemaFreeSource = source.replace(/^(https?):/, '');
  let canPlay = false;
  for (let i = 0; i < PLAYER_DOMAINS.length; i++) {
    const domain = `${PLAYER_DOMAINS[i]}?`;
    const domainWithSlash = `${PLAYER_DOMAINS[i]}/?`;
    if (
      (schemaFreeSource.indexOf(domain) !== -1) ||
      (schemaFreeSource.indexOf(domainWithSlash) !== -1)
    ) {
      canPlay = true;
      break;
    }
  }
  return canPlay;
};

```

There are no errors, the flow seems correct, it creates the correct m3u8 playback plungin but there is nothing played, **what am I missing** ?

(I try to avoid use of lodash that is why you have those ugly for loops)

**Comment by leandromoreira** [comment]
> In the current clappr - PlayerInfo.playbackPlugins is empty, where did the plugin registry go ?

I tested at http://cdn.clappr.io/ and `player.core.playerInfo.playbackPlugins` is working, the [loader component](https://github.com/clappr/clappr/blob/master/src/components/loader/loader.js#L85) is responsible to manage all plugins `player.loader.playbackPlugins || player.loader.containerPlugins`

> This means playbackPlugins are global and shared between multiple instances of the plugin(if a page contains multiple videos) ?

No, they're by instance.

> There are no errors, the flow seems correct, it creates the correct m3u8 playback plungin but there is nothing played, what am I missing ?

Did you add it to `Clappr.Player` constructor? If yes, after you try to play (the first play will be discarded, since you didn't bind PLAYBACK_PLAY to retry to play), try to call `player.play()` on console.

**Comment by towerz** [comment]
@iongion it seems you are only missing a call to `render()` when instantiating `this._playback`.

Try changing the `play()` method to something like this:
```javascript
play() {
    if (!this._playback) {
      const decodedSourceURL = this.hashToUrl(this.options.src);
      const PlaybackPluginClass = this.findPlaybackPlugin(decodedSourceURL);
      if (PlaybackPluginClass) {
        this.options.src = decodedSourceURL;
        console.debug('constructing playback plugin instance', this.options);
        this._playback = new PlaybackPluginClass(this.options);
        this.$el.append(this._playback.render().el);
        this._playback.play();
      }
    } else {
      this._playback.play();
    }
  }
```

**Comment by iongion** [comment]
@towerz Thank you so much for answer - I have added the element as you instructed but still I am unable to see any video being displayed:

I am testing against a local mp4 or m3u8 and the screen is always black, as below

![image](https://cloud.githubusercontent.com/assets/867609/14531452/aa302158-025d-11e6-8ac3-131c06e2ad30.png)

When I use m3u8 the src gets trasformed into the blob url you see in the screenshot.
When I use an mp4, the url to the mp4 is present

But nothing is played or at least, nothing is showed playing, I probably am missing something else.
The code that I pasted above is the entire class.
Do I still need to implement the bindEvents if I do not want to change playback behavior ?

**Comment by towerz** [comment]
@iongion actually, this code is working properly, but there are some small issues with this approach. In order to make your playback proxy work, you have to actually proxy the inner playback methods (play, pause, seek, etc) and some of its properties, as well as bubbling up the playback events.

A working example would look like this:
```javascript
import { Events, Playback } from 'Clappr';

const expected = 'http://cdn.clappr.io/highline.mp4';

const PLAYER_DOMAINS = [
  '//player.keecast.tv',
  '//player.keemotion.com',
];

export default class KeemotionVideoHashSource extends Playback {

  get name() { return 'keemotion_video_hash_source'; }

  constructor(options) {
    super(options);
    this.options = options;
  }

  bindPlaybackEvents() {
    [
      Events.PLAYBACK_PROGRESS, Events.PLAYBACK_TIMEUPDATE, Events.PLAYBACK_READY,
      Events.PLAYBACK_BUFFERING, Events.PLAYBACK_BUFFERFULL,  Events.PLAYBACK_SETTINGSUPDATE,
      Events.PLAYBACK_LOADEDMETADATA, Events.PLAYBACK_HIGHDEFINITIONUPDATE,  Events.PLAYBACK_BITRATE,
      Events.PLAYBACK_LEVELS_AVAILABLE, Events.PLAYBACK_LEVEL_SWITCH_START, Events.PLAYBACK_LEVEL_SWITCH_END,
      Events.PLAYBACK_PLAYBACKSTATE, Events.PLAYBACK_DVR, Events.PLAYBACK_MEDIACONTROL_DISABLE,
      Events.PLAYBACK_MEDIACONTROL_ENABLE, Events.PLAYBACK_ENDED, Events.PLAYBACK_PLAY, Events.PLAYBACK_PAUSE,
      Events.PLAYBACK_STOP, Events.PLAYBACK_ERROR, Events.PLAYBACK_STATS_ADD, Events.PLAYBACK_FRAGMENT_LOADED,
      Events.PLAYBACK_LEVEL_SWITCH
    ]
      .forEach((evt) => this.listenTo(this._playback, evt, (...args) => this.trigger(evt, ...args)))
  }

  findPlaybackPlugin(source) {
    const playbackPlugins = this.options.loader.playbackPlugins;
    for (let i = 0; i < playbackPlugins.length; i++) {
      const PlaybackPluginClass = playbackPlugins[i];
      if (PlaybackPluginClass.canPlay(source)) {
        return PlaybackPluginClass;
      }
    }
    return null;
  }

  hashToUrl(hash) {
    // TODO: write decoder
    return expected;
  }

  play() {
    if (!this._playback) {
      const decodedSourceURL = this.hashToUrl(this.options.src);
      const PlaybackPluginClass = this.findPlaybackPlugin(decodedSourceURL);
      if (PlaybackPluginClass) {
        this.options.src = decodedSourceURL;
        console.debug('constructing playback plugin instance', this.options);
        this._playback = new PlaybackPluginClass(this.options);
        this.$el.append(this._playback.render().el)
        this.bindPlaybackEvents()
        this.settings = this._playback.settings
        this.trigger(Events.PLAYBACK_SETTINGSUPDATE)
        this._playback.play();
      }
    } else {
      this._playback.play();
    }
  }

  // TODO: proxy playback methods
  isPlaying() {
    return this._playback && this._playback.isPlaying() || false
  }

  pause() {
    this._playback && this._playback.pause()
  }
  // ...
}

KeemotionVideoHashSource.canPlay = (source) => {
  // should return true for the supported media source
  const schemaFreeSource = source.replace(/^(https?):/, '');
  let canPlay = false;
  for (let i = 0; i < PLAYER_DOMAINS.length; i++) {
    const domain = `${PLAYER_DOMAINS[i]}?`;
    const domainWithSlash = `${PLAYER_DOMAINS[i]}/?`;
    if (
      (schemaFreeSource.indexOf(domain) !== -1) ||
      (schemaFreeSource.indexOf(domainWithSlash) !== -1)
    ) {
      canPlay = true;
      break;
    }
  }
  return canPlay;
};
```
I would suggest instead of doing this, to create an empty playback (that renders nothing) that implements the `canPlay`. Then create a UICorePlugin that listens for the CORE_CONTAINERS_CREATED  event which replaces instances of the KeemotionVideoHashSource playback with the actual playback implementation with the computed source. This plugin would be responsible for implementing `hashToUrl`.

**Comment by iongion** [comment]
Ok @towerz, I will follow the new guideline but first I need to:

1) Understand what UICorePlugin is and how it works
2) Keep KeemotionVideoHashSource plugin with only canPlay class method and hashToURL - but then who calls hashToURL ?

Is this an up to date UICorePlugin that I can use as example ?
https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js

**Comment by towerz** [comment]
@iongion about what I said, there's only one detail that's wrong. Since you only need to switch sources, there's no need to create a UICorePlugin. Instead, you should create a CorePlugin.

A CorePlugin (and UICorePlugin) is a plugin type that has access to the player core element. This means it has read/write access to the player state, containers and the whole player UI.

The simplest example of a CorePlugin that can do what you need would be something like this:
```javascript
import {CorePlugin, Events, Playback} from 'Clappr'

const expected = 'http://cdn.clappr.io/highline.mp4'

const PLAYER_DOMAINS = [
  '//player.keecast.tv',
  '//player.keemotion.com',
]

export class KeemotionVideoHashResolver extends CorePlugin {
  get name() { return 'keemotion_video_hash_resolver'}

  bindEvents() {
    this.listenTo(this.core, Events.CORE_CONTAINERS_CREATED, this.onContainersCreated)
  }

  onContainersCreated() {
    this.core.containers.forEach((container) => {
      if (container.playback.name == KeemotionVideoHashSource.prototype.name) {
        container.destroy()
        this.core.createContainer(hashToUrl(container.src), container.options)
      }
    })
  }

  hashToUrl(hash) {
    // TODO: write decoder
    return expected
  }
}

export class KeemotionVideoHashSource extends Playback {
  get name() { return 'keemotion_video_hash_source' }
}

KeemotionVideoHashSource.canPlay = (source) => {
  // should return true for the supported media source
  const schemaFreeSource = source.replace(/^(https?):/, '')
  let canPlay = false
  for (let i = 0; i < PLAYER_DOMAINS.length; i++) {
    const domain = `${PLAYER_DOMAINS[i]}?`;
    const domainWithSlash = `${PLAYER_DOMAINS[i]}/?`;
    if (
      (schemaFreeSource.indexOf(domain) !== -1) ||
      (schemaFreeSource.indexOf(domainWithSlash) !== -1)
    ) {
      canPlay = true
      break
    }
  }
  return canPlay
}

export default {
  KeemotionVideoHashResolver,
  KeemotionVideoHashSource
}
```
Notice that I just broke your code into two plugins:  a core plugin (that only changes the source marked by a given playback type) and a dummy playback (used for detecting the type of source and marking it as a source to be processed).

If you need further help with this, please reopen this issue so we can track it.

**Comment by iongion** [comment]
Modified a bit your suggestion and mine, it works perfectly:

```
import { Events, Playback, CorePlugin } from 'clappr';
import Decoder from '~/keemotion/player/parsers/Decoder';

const decoder = new Decoder();

class KeemotionVideoHashSource extends Playback {
  get name() { return 'keemotion_video_hash_source'; }
}
KeemotionVideoHashSource.canPlay = (source) => {
  // should return true for the supported media source
  return decoder.canDecodeURL(source);
};

class KeemotionVideoHashResolver extends CorePlugin {
  get name() { return 'keemotion_video_hash_resolver'; }
  constructor(core) {
    super(core);
    this.core = core;
  }
  bindEvents() {
    this.listenToOnce(this.core, Events.CORE_CONTAINERS_CREATED, this.onContainersCreated);
  }
  onContainersCreated() {
    this.core.containers.forEach((container) => {
      if (container.playback.name === KeemotionVideoHashSource.prototype.name) {
        container.destroy(); // remove existing container as a new container will be created
        const url = decoder.decodeURL(container.options.src);
        container.options.src = url; // override the src with the decoded value
        this.core.createContainer(url, container.options); // create an actual container for the decoded url
      }
    });
  }
}

export default {
  KeemotionVideoHashSource,
  KeemotionVideoHashResolver,
};

```

I will return with more info when I tackle the custom json playlist feature, once again, thank you for your big support!

**Comment by leandromoreira** [comment]
I think u can remove this constructor.

```
  constructor(core) {
    super(core);
    this.core = core;
  }
```

**Comment by iongion** [comment]
Indeed :) :+1:
