### ISSUE TITLE
Multiple streams in different definition level

### ISSUE THREAD

**Issue by jayrmotta** [clappr/clappr#512]
How can I do something like globo.com's clappr instance which has a video definition selector?

![image](https://cloud.githubusercontent.com/assets/349948/9022597/06551e24-3852-11e5-9c1e-8885209340e1.png)

The documentation mentions this [level selector plugin](https://github.com/clappr/clappr-level-selector-plugin) but it's quite different from globo.com's instance. Yet, it has almost no documentation so I would have to dig into the code to really understand, if you guys help me out it would be great :)

If the globo.com's version of clappr isn't available, is there any other HTML5 player as good as clappr with definition selector available in the market that you guys would recommend?

**Comment by towerz** [comment]
@jayrmotta The quality selector on globo.com applies only to the progressive download delivery. It's not related to the [level selector plugin](http://github.com/clappr/clappr-level-selector-plugin), which reads the multiple qualities available on a HLS stream and lets you set a fixed quality to be streamed.

Since the globo.com implementation is used for changing the source URL for the video, it's tightly coupled with the delivery method used. You could easily implement this with a plugin that has the list of the URLs for each quality and when selecting a given quality, change the video source of the player.

**Comment by towerz** [comment]
I don't think there's a HTML5 player implementation that is ready for this, but I don't think you'll have any issues implementing a plugin for that using Clappr.

**Comment by jayrmotta** [comment]
@towerz Thanks for the quick answer!

I'm not a video specialist but I imagine that I'd have to work in a lower level while streaming multiple sources and keeping the video playing from the place the last source has stopped. Also, it would be nice to have a mechanism to increase or decrease definition automatically in order to avoid buffers.

Do you have any thoughts on that?

**Comment by towerz** [comment]
@jayrmotta About playback from multiple sources, you are correct. You need to synchronize the sources manually, waiting for the metadata from the new source to be ready and then seeking to the last position the previous source was playing. You'll need to implement a few tricks to keep both sources sync'ed correctly, but basically you just need to do that.

About automatically increasing/decreasing definition based on bandwidth, there are some options available. You don't need to implement this manually, you could use a HTTP streaming technology, such as HLS, DASH, and others.
