### ISSUE TITLE
Player does not initialize as it fails to load a dependency that seems to have been taken off

### ISSUE THREAD

**Issue by lkkadiri** [clappr/clappr#519]
GET http://cdn.clappr.io/latest/assets/HLSPlayer.swf?inline=1 request fails even with a specified version of clappr(0.1.7) is being used. Tried upgrading to '0.2.1' and the player does not initialize anymore. Is there any documentation on breaking changes? This affects all our environments. We are currently specifying clappr in our node application and requiring clappr.

**Comment by konashark** [comment]
I entered a similar issue earlier today, but I found moving to 0.2.1 fixed the issue and worked without changes (my previous version was 0.1.1) and got rid of the dependency, so I closed the issue. Did you clear your browser cache after changing versions?

**Comment by lkkadiri** [comment]
@konashark I have tried clearing my cache and it does not seem to work and i tried building the latest master locally to only find out the bin/hook.js is no more included in the project and the build seems to fail.

**Comment by konashark** [comment]
Oh? I never build anything, I just copy the .js files out of 'dist' and drop them into my project. (BTW: I do not represent Clappr in any way, just trying to help since I had the same problem this morning and I was lucky that the update worked out of the box for us.) Good luck!

**Comment by lkkadiri** [comment]
@konashark Thanks for the suggestions, still no luck for us here. I was trying to build as a last resort but i can only build the stable version which still uses that cdn dependency for the hls swf file.

**Comment by thiagopnts** [comment]
@lkkadiri yes, we changed the way we build the player, I'll update update the README with the right instructions, now you should just `npm run build` or `npm run release`

**Comment by lkkadiri** [comment]
Yeah we figured that out thanks @thiagopnts. Also opening a PR to address the playbackhls that still uses window.Clappr

**Comment by towerz** [comment]
@lkkadiri clappr 0.1.x had a limitation that prevented us to lock the default base url for the assets to the current version. From 0.2.0 onward we'll not have this problem, unless the `baseUrl` parameter is explicitly set to point to `latest`.

Since we were in the process of changing the way the player is built, this ended breaking instances of 0.1.x without setting `baseUrl`. It's now fixed on 0.2.2, and using `latest` will not break loading assets anymore.

**Comment by jfairley** [comment]
@towerz We're actually using CommonJS + Browserify to import clappr. For this reason we were surprised that a CDN is getting used at all (the swf is coming from CDN). Are there future plans to completely remove the depedency on the CDN when using CommonJS?

**Comment by towerz** [comment]
@jfairley Since the beginning we planned for Clappr being hosted either on a CDN or imported directly in your code and having the assets hosted on your own server.

There are some assets that we use, such as the SWF files, that aren't packed in the bundle. Thus, in order to import them we use a base URL to load these assets. Currently, the default value for the base URL is `//cdn.clappr.io/<version>`. This way you can stop using the CDN by pointing the `baseUrl` parameter to your own server.

Are you creating your own Player class or using the default Clappr.Player? If you are extending this class, you could just override the `baseUrl` by adding it directly to the player options.

**Comment by towerz** [comment]
@jfairley Just opened #526 with your request.

**Comment by jfairley** [comment]
Nice. Thanks @towerz. I'll start looking into how this change affects our app.
