### ISSUE TITLE
Fullscreen on Play?

### ISSUE THREAD

**Issue by JOOKER69** [clappr/clappr#527]
Hi,
i have a question:
it is possible to make the player fullscreen on play?
or is there a function to run with javascript to run it in fullscreen?
also maybe possible to run the player in portrait only mode on fullscreen (for mobile devices)?

greetz

**Comment by leandromoreira** [comment]
Hi @JOOKER69 I don't know if I understood your question but I'm afraid that the answer is no.

In order to use fullscreen API you usually **need to require the fullscreen** within an user action (user click...), even if you listen to when the [container](https://github.com/clappr/clappr/blob/master/src/components/container/container.js#L111) is playing you won't get the fullscreen on play. The example down bellow won't work.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Clappr Fullscreen test</title>
    <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
  </head>
  <body>
    <div id="player"></div>
    <script>
      var player = new Clappr.Player({source: "http://techslides.com/demos/sample-videos/small.mp4", parentId: "#player"})
      player.listenTo(player.core.mediaControl.container, Clappr.Events.CONTAINER_PLAY, function() {
        player.core.mediaControl.container.fullscreen()
      })
    </script>
  </body>
</html>
``` 
A new [spec about fullscreen](https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen) is being made, maybe in a future it'll be possible.

What you could do is: when the container is playing you resize the player to fill the page.

```javascript
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Clappr Fullscreen test</title>
    <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
  </head>
  <body>
    <div id="player"></div>
    <script>
      var player = new Clappr.Player({source: "http://techslides.com/demos/sample-videos/small.mp4", parentId: "#player"})
      player.listenTo(player.core.mediaControl.container, Clappr.Events.CONTAINER_PLAY, function() {
        player.resize({height: 720, width: 1080})
      })
    </script>
  </body>
</html>
```

**Comment by towerz** [comment]
@JOOKER69 We don't have an event for when the user clicks on the poster, but you could listen for clicks on it to go fullscreen when the user requests to play. This way you will piggyback on an user interaction and work though user interaction restriction on the fullscreen api.

I believe this will work, using the sample from @leandromoreira: 
```javascript
var player = new Clappr.Player({source: "http://techslides.com/demos/sample-videos/small.mp4", parentId: "#player"})
player.getPlugin('poster').$el.on('click', function() {
  player.core.mediaControl.toggleFullscreen();
});
```
Just keep in mind this won't work when `autoPlay` is set to true.
