### ISSUE TITLE
identify the location of the SWF file

### ISSUE THREAD

**Issue by cherihung** [clappr/clappr#530]
Will there be a way to specify the location of the SWF file in the player API?
Similar to other video library (videojs, jwplayer) that it has a param to specify where to look for flash file if not in the webpack publicPath. Would be useful for self-hosting project that isn't using webpack or have an alternative location for the flashfile. (would be useful to have a release w/o the hashed file name. though I could build that locally)

**Comment by towerz** [comment]
@cherihung currently we have a way to set the `baseUrl` for looking for assets, using the aforementioned parameter. It's set by default to webpack `publicPath`.

Before migrating to webpack there was a parameter called `swfPath` which has been removed since then, but we could easily re-enable this functionality. 

Just let me know whether this is really necessary, since you can host clappr files yourself without changing anything. If you just copy the dist/ folder contents to host and clappr will automatically load the asset files from there, instead of the clappr cdn.

**Comment by cherihung** [comment]
My webpack projects defaults to include path and name for swf and font files (file-loader?[path][name].[ext]). So I was having problem since Clappr defaults to looking for assets in `publicPath` of a project. `baseUrl` would only kind of work if I can ensure 'publicPath` of the project using my implementation of Clappr is the same. 

Right now, I'm using require.context(...) to dynamically change clappr's require statements. I was going to ask for `swfPath` but then I see the same problem with font files too (hence using require.context..()). If there's a better Clappr way to do this, please let me know :)  thanks!

**Comment by towerz** [comment]
@cherihung I take you are bundling Clappr inside your own webpack bundle, instead of an external dependency.

If you are doing that, I suggest you change the entry point for Clappr from dist/clappr.min.js to src/main.js. Doing this will make webpack bundle the Clappr source inside your own application and generate asset chunks using your on naming rules. 

The only thing you need to remind is that Clappr uses ES6, so you need to use babel loader to build correctly. Just add this setting to your webpack configuration:
```javascript
{
   //...
  resolve: {
    alias: { Clappr: 'clappr/src/main.js' }
  }
```
Please let me know if this works for you.

**Comment by cherihung** [comment]
I tried this out. But it'd add more loaders and overhead to the project with bable and sass loader. it's not a huge deal but it'd require me to make any consumer project deal with all the various assets included or may be included in Clappr. 
So I decided to just tweak the configuration to specifically load clappr font files + swf to publicPath. it's the simplest solution. 

thanks for you all your help!
