### ISSUE TITLE
Merge UIObject/Plugins remove and destroy methods into a single method

### ISSUE THREAD

**Issue by towerz** [clappr/clappr#537]
**_1 Upvote**_ Since some of the player elements are implemented directly using `UIObject`s instead of plugins, there have been some confusion around implementing the `destroy` method used by plugins.

I think we should merge both methods into a single `remove` method that removes the element from it's parent tree and unbinds event listeners. This way we can avoid confusing users as well as listener reference leaks.

**Comment by flavioribeiro** [comment]
+1

**Comment by joaopaulovieira** [comment]
I don't know if this is still a change that should be made because of the time that has passed, but doing today would be a breaking change and the `destroy` method would have to be keeped for plugins that overwrite it.
It causes a little more confusion  :sweat_smile:
But that change could go into a major version, what you think?

**Comment by towerz** [comment]
@joaopaulovieira indeed, it is a breaking change. I agree with you that this should go into a major version, or at least in our 0.3.x API revision.
