### ISSUE TITLE
HLS stream poor quality compared to loading in VLC or Safari

### ISSUE THREAD

**Issue by chovy** [clappr/clappr#544]
When I load an HLS stream through clappr its pretty bad quality, blurry and choppy.
If I load the same stream in VLC or Safari it plays as expected in HD.

**Comment by ebuildy** [comment]
Is it a multi-bitrate stream?

Please post your m3u8 file URL, so it can be tested.

**Comment by towerz** [comment]
@chovy we need more information about this issue, as well as a URL for reproducing this issue.
- Are you on clappr 0.1.x or did you already updated to 0.2.x? There was an issue in our flashls implementation which forced level capping when the frame drop ratio (skipped frames / presented frames) was bigger than 0.2. This was disabled by default in 0.2.5.
- What kind of browser are you using? We have experienced this issue mostly running on Firefox.

**Comment by chovy** [comment]
I'm on 0.2.x now.

I'm in chrome and here's a sample stream. All my streams have this problem.

http://pac12hd2-lh.akamaihd.net/i/p12netw_delivery@132840/master.m3u8

**Comment by ebuildy** [comment]
Woa, so many bitrates supported, maybe this is too much and Clappr is always "switching" them

**Comment by ebuildy** [comment]
Also your video segments seem very "little" 

![]
(http://b3.ms/PjL9yGQwnqXD)

**Comment by towerz** [comment]
@chovy I tested your stream on http://cdn.clappr.io and it kept running steadily between bitrates 2328000 and 4728000. What version of clappr are you using? Is it older than 0.2.5?

**Comment by chovy** [comment]
i'm using version 0.2.10

**Comment by towerz** [comment]
@chovy I tested locally using `0.2.10`, and it's playing ok for me. Still running steadily and switching between bitrates 2328000 and 4728000. Could you please share your embed code here?

Using `0.2.12` I noticed a strange behavior. Since `0.2.11`, hardware acceleration for video decoding is enabled, but with hardware video decoder enabled it kept complaining about your ts fragments not starting with an I-Frame. Also I got some I/O errors loading fragments, usually in the lower bitrates.
