### ISSUE TITLE
Quicktime overlay on iPhone hides clappr controls

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#563]
Ok, another iOs problem !

With iPhone (iOs 7.1.2), movie is launched in fullscreen directly, and it's ok. But when you come back into the webpage, there is a quicktime overlay over clappr and we can't access to the mediacontrol. 

Is there a trick to prevent that ?

**Comment by towerz** [comment]
Hi @irongomme, I don't have access to an iPhone with iOS 7.x, but I tested on both iOS 8 and 9.

We still lack support for touch events on the MediaControl, but it can be called with a tap on the player. We can't prevent the quicktime overlay to be shown (it's a feature built into the OS itself), but to avoid having the user tap to activate the controls, you could just show the controls whenever the video is paused. Since videos always play in fullscreen on the iPhone, and the video is paused when the user dismisses the fullscreen video, the controls would always be visible when the player exits fullscreen.

To avoid hiding the controls after some time, you could just set `hideMediaControl` to false in the player options, or directly in `player.core.mediaControl.options`.

**Comment by irongomme** [comment]
Thks @towerz i'll try it. This is à Blocking thing for me because i've added a channel choice over the player but I will try to find another trick for that .

**Comment by towerz** [comment]
@irongomme it just occurred to me that you could use the player poster to cover this quicktime overlay. Whenever the user exits the video, the player goes into the pause state I mentioned before. In this state, you could just display the MediaControl and the player poster. This way the player wouldn't seem to be broken.

**Comment by irongomme** [comment]
Finally, i'my going to this conclusion : a mobile app will be the best cross platform compromise !
