### ISSUE TITLE
MediaControl object available in Container plugins? Or MediaControlPlugin?

### ISSUE THREAD

**Issue by jazzmanro** [clappr/clappr#564]
Hi there,

Thanks for your great work.
During Clappr plugin development I am forced to always extend UICorePlugin as although my plugins are just placing additional content/controls in the media control bar (some of them having almost nothing to do with the playback), I don't have otherwise access to the MediaControl object.

Maybe the best idea would be a specific media control plugin? Or do you have any ideas how could I do better?

**Comment by towerz** [comment]
Hi @jazzmanro, I take you are trying to display content over the video, but tied to the MediaControl itself, showing/hiding with the controls layer. Is that right?

The MediaControl, although related to a single container, is not scoped to the container it controls. It is included in the player core, so in order to access it (or render into it) you have to write a UICorePlugin. Your approach is correct, according to how Clappr works.

Container plugins only have access to the container, and are related to the content being rendered, like watermarks, overlays, ads, etc. The container has no access to the MediaControl, because the Clappr architecture is based in a bottom up approach. Inner elements are not aware of their external environment, they can only access their own scope. The only action they should do to reach outside is triggering events.

**Comment by jazzmanro** [comment]
Thanks @towerz, so then I have no other choice. No problem to create UICorePlugins, just thought they are 'too much' for simply needing to insert some information in the MediaControl.
As I've said, maybe for the future it would be interesting to have a UIMediaControlPlugin that would be automatically recreated/rendered with the MediaControl as it is so tied to it.

Thanks again for your clarifications.
