### ISSUE TITLE
Play button occurs for flash on some browsers.

### ISSUE THREAD

**Issue by alparslanahmed** [clappr/clappr#571]
Hi, i have a live stream autoplay option true. On some browsers, some computers a play button occurs on flash. I know thats not clappr problem directly i see that on video.js too. How can i remove this?

![alt text](http://oi59.tinypic.com/dgqmie.jpg "")

**Comment by towerz** [comment]
Hi @alparslanahmed, this is related to some browsers implementing flash blocking natively. I think it's related to the player dimensions.

Since the native flash blocking is targeted at ads that use flash, I think it uses the swf object dimensions (width, height) to determine whether it's being used for playing content or displaying ads. If you call `player.resize()` to an allowed size when the play button is displayed, the video starts to play automatically.

**Comment by alparslanahmed** [comment]
Its works, thanks for help!
