### ISSUE TITLE
No CONTAINER_SEEK + CONTAINER_STATE_BUFFERING on iPhone fullscreen

### ISSUE THREAD

**Issue by tcacciatore** [clappr/clappr#573]
I'm using clapper on both iPhone and iPad. 
When playing some videos on iPhone, the player goes directly in fullscreen mode and some events are not sent (CONTAINER_SEEK and CONTAINER_STATE_BUFFERING).

**Comment by leandromoreira** [comment]
isn't the default behavior to go full screen? also arent the events still being sent?

**Comment by joseym** [comment]
I think I'm having the same issue, but with `PLAYER_SEEK`.

The event fires as expected in chrome, but when testing on an iPhone the `PLAYER_SEEK` event never fires.

**Comment by leandromoreira** [comment]
still a bug?

**Comment by kslimani** [comment]
For __Events.CONTAINER_SEEK__ event, this is because it is trigger only by container seek() method (ie: if used seek video using Clappr media controls, not by observing video element events/state).

Please note, i am describing behaviour for Safari browser on iOS device for __'html5_video'__ playback using native mode.

BTW, on my tests, `Events.CONTAINER_STATE_BUFFERING` and `Events.CONTAINER_STATE_BUFFERFULL` are properly trigger.

IMO, it would usefull if container could be aware that player has seeked to new position (maybe with a new container event ?).

Please also note that it seems there is a bug _(not confirmed if it is a bug or an expected behaviour)_ with Safari on iOS : using 'html5_video' playback, __(VOD playback type)__ when you seek video :

* if source is .mp4, the `playing` event is __not__ fired
* if source is .m3u8, the `playing` event is fired

With other Browser, the `playing` event seems to be trigger _(tested Chrome on iOS)_

I am currently doing tests, i will post again if have updates.

**Comment by kslimani** [comment]
My tests results on Safari [HTMLMediaElement](https://developer.apple.com/reference/webkitjs/htmlmediaelement) after a seek _(ie: set a value to `currentTime` property)_ :

*  does __not__ trigger `playing` event if video source is .mp4
*  does trigger `playing` event if video source is .m3u8

On Chrome and Firefox, event `playing` is properly trigger if source is .mp4
_(Also with .m3u8 but it is using HLS.JS, not native HTML5 video)_

Tested on

* Safari 10 with Mac OS X El Capitan 10.11.6
* Safari 9 with iPad and iOS 9.2

On current master  branch, Clappr container seek event is trigger only by container [seek()](https://github.com/clappr/clappr/blob/master/src/components/container/container.js#L302) method. 

This make it "hard" to track seek operation done by user with native iOS media controls. (_if listening only to container events_).

Maybe the 'html5_video' playback should use HTMLMediaElement `seeked` event to handle seek on Safari with iOS ?

**Comment by joaopaulovieira** [comment]
Both events `seek` and `seeked` are already being listened to be fired at the container layer: https://github.com/clappr/clappr-core/blob/master/src/playbacks/html5_video/html5_video.js#L71-L72
