### ISSUE TITLE
RFC: Add support to a broader feature check at Playback

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#627]
We set that the `Playback` holds a function [`isHighDefinitionInUse`](https://github.com/clappr/clappr/blob/2fa8ebe298d9458231c83fad88465ad11ce845e8/src/base/playback.js#L81) which is responsible for defining if a playback is using `HD` or not. (we mostly consider 720p as  HD)
## Problem 1

There will be lots of new "features" such as: 4K, 8K, FullHD, 3D, 360... and it'd be silly to add functions like: `isFullHighDefinitionInUse, is4KinUse` ...
## Solution 1

Add a function `isFeatureInUse` to check broader features.

``` javascript
Playback.VideoFeature.HD = "HD"
Playback.VideoFeature.FULL_HD = "fullHD"
Playback.VideoFeature.V4K = "4K"
//...

playback.isFeatureInUse(Playback.VideoFeature.V4K)
```

**Comment by tchakabam** [comment]
:+1:

**Comment by tchakabam** [comment]
The idea to make much more generic methods on Playback API I think is very good :) Therefore, I would totally support this kind of implementation proposed here.

But now for the use-case in specific exemplified, I think it becomes obvious that the information whether we are playing HD or 4K, is already contained in some way, or should be accessible via extension of `AdaptivePlayback`. There should just be already an API that tells us: Is a quality level within or above a certain resolution active (that's something the current API can do) and also, what is the currently played quality level in buffer (may be a detail we need to work out more clearly as it is important actually to have that I think). Now if we have such an API as the foundation of a playback implementation, then these kind of feature-activated-query methods become implementable in a generic non-playback-tech specific way on top of that adaptive API. Because then we can just go over all video qualities and check if a specific resolutions are active or not. Add these as helper methods to our playback base-class and thus they will be part of all implementations without touching them in specific. What do you think?
