### ISSUE TITLE
Level Selector plugin stopped working

### ISSUE THREAD

**Issue by madmarten** [clappr/clappr#638]
I don't know when, but think it's not more than a couple of weeks, the Level Selector plugin stopped working and made the whole player failing to load. See bottom player at http://beta.adventistplay.se/media/html/clapprvod.html

Error message is: external undefined plugin on core array

The code for the plugin doesn't seem to have changed for months, so I believe some changes has been made to the player making the plugin to fail loading. Is it possible to get it working again?

**Comment by towerz** [comment]
This error is due to a type enforcement implemented on the plugin Loader. I'm not sure why this happened to you with the latest Level Selector implementation. There could be something missing in the plugin implementation.

There's another detail about the plugin: it currently does not support the default HLS implementation on Clappr, based on hls.js. It only supports the previous implementation, based on FlasHLS. We're still working on an update for that.

**Comment by towerz** [comment]
The level selector has been fixed to work with the latest version of Clappr. As I mentioned before, it will only work if you are using the FlasHLS playback, but I'm working on a new version supporting hls.js as well.

**Comment by flavioribeiro** [comment]
:metal: congratz @towerz

**Comment by dayvson** [comment]
:beers: @towerz

**Comment by madmarten** [comment]
I have now tested and can confirm it is working again. Tank you!
