### ISSUE TITLE
player.mute() return volume to previews value

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#675]
Try change the volume, and them mute and unmute the player - you will get wrong volume level.

**Comment by FDiskas** [comment]
And on http://cdn.clappr.io/ website if I post in console `player.mute()` in control-bar the volume indicator is not updated, but volume is muted.

**Comment by flavioribeiro** [comment]
@FDiskas it seems we have two different issues here. The first one is regarding volume level persistence when toggling mute/unmute, while the seconds one is related to the volume button state when using player API. There's a [guideline](https://github.com/clappr/clappr#guideline-to-open-an-issue-bug) to open issues and I kindly ask you to follow them in order to help the improvement of the project overall.

**Comment by FDiskas** [comment]
I do not care. Just ignore all my opened issues :)

**Comment by FDiskas** [comment]
So is this to hard to reproduce? Just on cdn.clappr.io set the volume to 50 and in console enter `player.mute()` and then `player.unmute()` and you will see the difference :P
