### ISSUE TITLE
Samsung galaxy note 10.1GT-N8000 record displays as live

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#681]
Video displyed as LIVE stream. Wrong.

http://jsbin.com/qolupimaxa/edit?html,js,output
```
Mozilla/5.0 (Linux; Android 4.1.2; GT-N8000 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36
```

**Comment by FDiskas** [comment]
Why you closed the issue? It is still not fixed

**Comment by leandromoreira** [comment]
sorry

**Comment by leandromoreira** [comment]
is this still an issue?

**Comment by FDiskas** [comment]
:sheep: :it:

**Comment by FDiskas** [comment]
Yes the problem is still here.

**Comment by towerz** [comment]
We can't reproduce the issue on any other android device we have. 

Probably the device is reporting the video duration incorrectly, and the player interpreted the wrong duration as in a live video:
```javascript
return [0, undefined, Infinity].indexOf(this.el.duration) >= 0 ? Playback.LIVE : Playback.VOD
```
Since we can't reproduce the problem reported and seemingly it only happens in a specific device, we'll close this issue. If someone else is able to reproduce the issue and can work on a fix for it just reopen and submit a PR.
