### ISSUE TITLE
如何自定义 (How to Customize media control bar)

### ISSUE THREAD

**Issue by liuyukk26** [clappr/clappr#706]
怎么能隐藏控制条？怎么让视频拉伸满屏幕

**Comment by leandromoreira** [comment]
<hr>
我已经使用谷歌翻译  translate.google.com，我认为，你的母语是中国人，我很抱歉，我不知道你的语言，但我想你问过：

*您如何隐藏控制栏？对于这一个，你可以开始 `chromeless` (github.com/clappr/clappr#chromeless）或'disable`在创建后的媒体控制。
*如何让视频全屏拉伸？我不明白这个问题。
<hr>
I have used google translator (https://translate.google.com/) and I supposed that your native language is Chinese and I am sorry that I don't know  your language, but I think you've asked:

* How you can hide the control bar? For this one you can either start [`chromeless`](https://github.com/clappr/clappr#chromeless) or `disable` the media control after its creation.
* How to make the video full screen stretch? I don't understood this question.

<hr>

**Comment by me-vlad** [comment]
about "full screen stretch" - I think that @liuyukk26 asked how to go fullscreen programmaticaly for chromeless player or resize player to fit container size (adaptive player size).

@leandromoreira , correct me if Im wrong
fullscreen:
``` javascript
var player = new Clappr.Player({source: "http://your.video/here.mp4", parentId: "#player"});
player.setFullscreen();
```

adaptive resize:
``` javascript
function resizePlayer(){
    var aspectRatio = 9/16,
        newWidth = document.getElementById('liveplayer').parentElement.offsetWidth,
        newHeight = newWidth * aspectRatio;
    player.resize({width: newWidth, height: newHeight});
}
resizePlayer();
window.onresize = resizePlayer; 
```

**Comment by towerz** [comment]
@liuyukk26 @me-vlad About the fullscreen transition on play, I already mentioned this on #527. There are restrictions on the browser Fullscreen API that prevent entering fullscreen programatically, except during an user interaction. To make this work correctly, we should only transition to fullscreen programatically during a click/touch handler.

We still don't have a public method for the player to enter fullscreen, but with the current API, you could use something like that to enter fullscreen when playing:
```javascript
var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  parent: '#player-wrapper',
  mute: true,
  height: 360,
  width: 640
});
player.getPlugin('poster').$el.on('click', function() {
  player.core.mediaControl.toggleFullscreen();
});
```
Since this is one of the most common questions/requests, I'll create an issue to propose adding an embed option to enter fullscreen on play, and a `toggleFullscreen()` method to the public interface of the `Player` object.
