### ISSUE TITLE
Cross domain failures new to versions 0.2.14 - 0.2.28

### ISSUE THREAD

**Issue by konashark** [clappr/clappr#745]
I just upgraded from 0.2.1 to 0.2.28 and now ever time I try to play one of our HLS streams, I get the following errors:
**XMLHttpRequest cannot load http://path_to_video_server/Frag1Num0.ts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.**

I meticulously went through each release and found that it started at 0.2.14. **The same streams all play fine prior to then.**

This is on a Mac OS 10.11.2 (El Capitan) running Chrome 47.xxx

Any idea what changes have caused this new security failure and what I can do to work around it? Preferably without server side changes which I may not be able to get.

**Comment by towerz** [comment]
@konashark in Clappr 0.2.14 the default HLS implementation was changed from [flashls](https://github.com/mangui/flashls) to [hls.js](https://github.com/dailymotion/hls.js).

The new implementation doesn't depend on Flash to play HLS content, instead using a MSE implementation in javascript. Since requests made in javascript are restricted by the browser to follow restrictions specified by [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) headers, the playlist and fragment responses by the server should allow access through the 'Access-Control-Allow-Origin' header.

It's not really a security failure, it's only configuration missing in the server hosting your HLS stream. If you aren't able to change the servers to return this header, hls.js won't work at all. Flashls playback is still provided in the Clappr bundle, so if you want to keep Clappr behaving like on prior versions, you can load Clappr forcing its use.

Just add `Clappr.FlasHLS` to the list of plugins when embedding Clappr, like:
```javascript
var player = new Clappr.Player({
  source: 'http://your.source/here.m3u8',
  // ...
  plugins: { playback: [Clappr.FlasHLS] }
});
```
Please let me know if this works for you.
