### ISSUE TITLE
Clappr not working with HLS in chrome or firefox

### ISSUE THREAD

**Issue by djevo1** [clappr/clappr#777]
Added player script and it only works in safari and nothing else.
![screen shot 2016-01-18 at 8 50 08 pm](https://cloud.githubusercontent.com/assets/16768999/12407416/18849bca-be25-11e5-8bf2-f54c2e38ba5a.png)

**Comment by hounvs** [comment]
Is there any error showing in the console?

**Comment by leandromoreira** [comment]
@djevo1 since we're using hls.js (a js hls implementation) you might be facing CORS problems, anyway is there any error on your console as @hounvs asked you?

**Comment by djevo1** [comment]
Not sure how to view the console, hosting it on a wordpress site. Should i just ssh into it?

---Sent from Boxer | http://getboxer.com

On January 19, 2016 at 9:00:20 AM EST, Leandro Moreira <notifications@github.com> wrote:@djevo1 since we're using hls.js (a js hls implementation) you might be facing CORS problems, anyway is there any error on your console as @hounvs asked you?  —Reply to this email directly or view it on GitHub.

**Comment by hounvs** [comment]
@djevo1, when you view the page in Chrome and Firefox, you should be able to pull up the Javascript console (Windows: Ctrl+Shift+i, Mac: CMD+Shift+i)

If you are seeing any error that says "Access-Control-Allow-Origin", it's a CORS issue and can be fixed by adjusting the headers on your streaming server. Firefox and Chrome have CORS enabled by default as a security measure whereas other browsers don't.

I see that you're using Wowza like I am. This is what I used to fix the problem for me: https://streamroot.readme.io/docs/wowza-configuration

Let me know if that was the issue
