### ISSUE TITLE
Playing multiple videos in sequence

### ISSUE THREAD

**Issue by ikkebr** [clappr/clappr#864]
Not sure if this is a feature request or a documentation request. 

I would like to have a list of videos and play them in order, one after the other (something like a playlist). 

There is a comment on #550 from @tjenkinson about implementing a load method that does that, but I couldn't find information how to use that anywhere.

**Comment by flavioribeiro** [comment]
@guialbuk also have the same question. I know we had a "closed source" plugin that did this thing, not sure if it's already being used and if the guys have plans to open source it. cc @thiagopnts

**Comment by towerz** [comment]
@ikkebr we are updating this "closed source" plugin that @flavioribeiro mentioned, and will publish this as soon as possible. It cannot be used as it is because there are some business logic from our product mixed within it.

**Comment by thiagopnts** [comment]
are we planning to support it on the player itself? I would keep it as a separate plugin

**Comment by towerz** [comment]
@thiagopnts it will be a separate plugin. In fact, most built-in plugins will be extracted into standalone versions.

This will help us avoid releasing the player just to update plugin versions.

**Comment by eseffair** [comment]
Hi @towerz, There is a forecast for a release of the plug-in?

**Comment by vix-simplex** [comment]
I did it - https://gist.github.com/vix-simplex/94ed1e3462b67561a33e384a878c4d3e

**Comment by joaopaulovieira** [comment]
Hi people, I created one [queue plugin](https://github.com/joaopaulovieira/clappr-queue-plugin) to play videos in sequence. It's not finished yet (I'll create the API to manipulate the video queue dynamically) but already works if the queue is configured at Clappr init.

Instead of use/update the Clappr architecture to handle multiple containers, the plugin manages the queue and it's responsible to load and play the media.

Feel free to comment/contribute (:
