### ISSUE TITLE
Playback resolution setting

### ISSUE THREAD

**Issue by Tkamiya** [clappr/clappr#878]
Hello,

I want to know how do I use "100%" value as resolution setting.
Currently, I'm using "640x360" as player resolution.
It looks like good in my laptop side but if I access via my smartphone, then the playback area is protruded.

The webpage is below.

http://thinkourfuture.ddns.net/wowza/wowza5/

**Comment by towerz** [comment]
Hi, @Tkamiya.

Clappr supports setting "100%" to its dimensions. You just need to embed the player using:
```javascript
var player = new Clappr.Player({
  // ...
  width: "100%",
  height: "100%"
})
```
The only restriction is that you have to set the parent element dimensions. Otherwise the player will always compute its size to 0x0.

I checked the webpage you mentioned, and the parent element (`<div id="player">`) has no explicit size. It currently computes to 660x360 because it contains the player, which in turn has an intrinsic size. If you change the player to occupy 100% of the parent space, you'll have to add explicit dimensions to the parent element, like:
```css
#player {
  width: 660px;
  height: 360px;
}
```
Please let me know if this works for you.

**Comment by Tkamiya** [comment]
Hi towerz,

Thank you for your information.
I added your information to parent element.
I can see it works properly on my laptop.
But if I access via my smartphone, then player is still protruded like attached picture file.
You can see the red selected area in this picture file.

![screenshot_2016-03-18-17-40-00](https://cloud.githubusercontent.com/assets/15607238/13872869/c02bf3d4-ed30-11e5-8f48-250a2ccb98ff.png)

I expect that the player resolution is changed automatically by each devices.

**Comment by towerz** [comment]
@Tkamiya it seems you have changed the player container correctly, but your responsive style is not resizing it to the right size.

I ran the chrome inspector simulating a Nexus 5X, and the player container is sized to 660x360, instead of being resized to fit the viewport width (411px in my test).

![screenshot 2016-03-18 14 58 03](https://cloud.githubusercontent.com/assets/989801/13887444/7db1f26c-ed1a-11e5-964b-929ad5429627.png)

Try adding responsive rules to the style of the `#player` element.
