### ISSUE TITLE
Is there a way to play .ts file without .m3u8?

### ISSUE THREAD

**Issue by GeorgySerga** [clappr/clappr#897]
**Browser**: Chrome 49, Firefox 45.

**OS**: Ubuntu 14.04

**Clappr Version**: 0.2.38

Hi. I try to play '.ts' videos through http progressive download. The player doesn't recognize source without the mimetype, and I did try "video/MP2T" (not working, "browser doesn't support..." message), "application/x-mpegURL" (no errors, works on Android phone, extremely high cpu usage), "video/mp4"(no errors, works on Android phone, extremely high cpu usage). It looks like simple http streaming is working properly (tested for .mp4 file), also hls streaming with hls.js play ts files just fine. Are there any ways to play '.ts' files without '.m3u8' playlist (i.e. `http://domain.com/video.ts` or `http://domain.com/stream?ip=224.1.0.100&port=2000` for live http streaming)? Console shows no errors. Thank you in advance.

**Comment by ronag** [comment]
No, this is not really possible since browsers don't support mp2t. The reason m3u8 is because that is handled by hls.js which rewraps the mp2t files into mp4. However, it will only do that together with m3u8. You would need to somehow modify hls.js to get this to work. Or just generate a single entry m3u8 file...
