### ISSUE TITLE
[FlasHLS] missing play event after starting paused LIVE stream

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#901]
**Browser**: ANY w/ flash support (reproduced on chrome, firefox)

**Clappr Version**: 0.2.39 - 0.2.40 (works fine with 0.2.38)

**Steps to reproduce**:

* enable flashls playback, add LIVE (not VOD) hls source
* start playing, click on pause then click on play button
* stream resumed (end PLAYER_PLAY event fired) just after second click on the player

Reproduced at http://cdn.clappr.io/

config tested with cdn.clappr.io:

``` javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [Clappr.FlasHLS]
});

player.on(Clappr.Events.PLAYER_PLAY, function() { console.log("PLAY!") });
player.attachTo(playerElement);
```

**Comment by towerz** [comment]
@me-vlad I managed to reproduce the error, but I believe the problem only occurs when stopping the video, not pausing. Your test stream does not have DVR enabled (at least for Clappr minimum DVR duration).

The problem was caused by the manifest loaded event being caught only on the first play. After stopping the video and then starting it again, the event is triggered but no longer listened by the playback, so the play event is not fired, and causing a lot of other problems.

I just pushed 6fde7d0, which fixes the error I just described. Please let me know if this works for you.

**Comment by me-vlad** [comment]
@towerz indeed this issue related only for live streams w/o DVR, for DVR enabled streams it worked f.e. with  
http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl-v3,audio-only=false).m3u8

https://github.com/clappr/clappr/commit/6fde7d05f79cf6c4f370a391af2af848dc7dc84c fixes this issue, thanks, Bruno   :+1:

**Comment by towerz** [comment]
Anytime! :+1:
