### ISSUE TITLE
Should the most recent release (0.2.41) really have been 0.3.0?

### ISSUE THREAD

**Issue by bikegriffith** [clappr/clappr#913]
Just curious about what mandates a minor version bump and wanted to open it for discussion.

To me, the change from the Poster font the the svg icons is a significant enough undertaking that it should be bumped (I did some things with the Poster typeface in plugins that I *think* will need reworked).

I understand it's your call ultimately, but I'd really like to know how you think about versions so I know what to pin to.

Thanks for all you do!

**Comment by towerz** [comment]
@bikegriffith we didn't consider bumping a minor version with this change because there were no significant or breaking API changes. All poster/media control changes were in their internal implementation and did not change their function, just the way buttons are rendered within those components.

We don't actually recommend simply overriding templates/styles in the built-in plugins. Instead of doing this, subclassing and overriding the rendering functions as well as the templates/styles is the safest way to do this.

There are some API breaking changes planned for the near future. Those changes are related to the way the media control, containers and playbacks are defined and initialized, and in my opinion would justify bumping a minor version.

The next minor version will also help reduce bundle sizes, both for clappr itself and for projects that use it.

About the typeface changes, could you please share with us what kind of changes you are doing, so we can better support this kind of customization?

**Comment by bikegriffith** [comment]
@towerz it wasn't really that big of a deal ... I mentioned it actually here https://github.com/clappr/clappr/issues/898 as just a workaround I was doing.  I guess I just need to disable my workaround :)

I look forward to the future changes!

Closing this down...
