### ISSUE TITLE
Player Timeline Too Wide

### ISSUE THREAD

**Issue by ronag** [clappr/clappr#925]
When a clip is loaded in the played, a small timeline (with indicator or current position) is displayed below.

However, as the timeline is as wide as the window, it's difficult to see whether you are exactly at the start or beginning.

I think the timeline needs to be squeezed a bit horizontally so that you have a small margin on each side.

**Comment by towerz** [comment]
@ronag are you referring to the seek bar? It was designed this way, but it's not a big problem since the user can drag the scrubber to both start/end positions, even if the mouse cursor leaves the player bounds. This drag behavior will work even on fullscreen.

**Comment by ronag** [comment]
@towerz: Well, I would say there are problem with the design since you cannot click to the start, only drag...

**Comment by towerz** [comment]
@ronag I don't think of this as a problem. The seekbar click is not really precise, specially for longer videos, since it has to map the click offset to a duration percentage. Dragging the scrubber is the option that's more precise, so it would be used more often when the user wants to seek to a given time.

Additionally, the media control as well as its style can be overridden, so if you need to add some padding or change the bar height for whatever reason, you would be able to do so.
